// Code generated by ent, DO NOT EDIT.

package pageview

import (
	"aux-system/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PageView {
	return predicate.PageView(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PageView {
	return predicate.PageView(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PageView {
	return predicate.PageView(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PageView {
	return predicate.PageView(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PageView {
	return predicate.PageView(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PageView {
	return predicate.PageView(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PageView {
	return predicate.PageView(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PageView {
	return predicate.PageView(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PageView {
	return predicate.PageView(sql.FieldLTE(FieldID, id))
}

// PageID applies equality check predicate on the "page_id" field. It's identical to PageIDEQ.
func PageID(v string) predicate.PageView {
	return predicate.PageView(sql.FieldEQ(FieldPageID, v))
}

// VisitorID applies equality check predicate on the "visitor_id" field. It's identical to VisitorIDEQ.
func VisitorID(v string) predicate.PageView {
	return predicate.PageView(sql.FieldEQ(FieldVisitorID, v))
}

// IsAdmin applies equality check predicate on the "is_admin" field. It's identical to IsAdminEQ.
func IsAdmin(v bool) predicate.PageView {
	return predicate.PageView(sql.FieldEQ(FieldIsAdmin, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PageView {
	return predicate.PageView(sql.FieldEQ(FieldCreatedAt, v))
}

// PageIDEQ applies the EQ predicate on the "page_id" field.
func PageIDEQ(v string) predicate.PageView {
	return predicate.PageView(sql.FieldEQ(FieldPageID, v))
}

// PageIDNEQ applies the NEQ predicate on the "page_id" field.
func PageIDNEQ(v string) predicate.PageView {
	return predicate.PageView(sql.FieldNEQ(FieldPageID, v))
}

// PageIDIn applies the In predicate on the "page_id" field.
func PageIDIn(vs ...string) predicate.PageView {
	return predicate.PageView(sql.FieldIn(FieldPageID, vs...))
}

// PageIDNotIn applies the NotIn predicate on the "page_id" field.
func PageIDNotIn(vs ...string) predicate.PageView {
	return predicate.PageView(sql.FieldNotIn(FieldPageID, vs...))
}

// PageIDGT applies the GT predicate on the "page_id" field.
func PageIDGT(v string) predicate.PageView {
	return predicate.PageView(sql.FieldGT(FieldPageID, v))
}

// PageIDGTE applies the GTE predicate on the "page_id" field.
func PageIDGTE(v string) predicate.PageView {
	return predicate.PageView(sql.FieldGTE(FieldPageID, v))
}

// PageIDLT applies the LT predicate on the "page_id" field.
func PageIDLT(v string) predicate.PageView {
	return predicate.PageView(sql.FieldLT(FieldPageID, v))
}

// PageIDLTE applies the LTE predicate on the "page_id" field.
func PageIDLTE(v string) predicate.PageView {
	return predicate.PageView(sql.FieldLTE(FieldPageID, v))
}

// PageIDContains applies the Contains predicate on the "page_id" field.
func PageIDContains(v string) predicate.PageView {
	return predicate.PageView(sql.FieldContains(FieldPageID, v))
}

// PageIDHasPrefix applies the HasPrefix predicate on the "page_id" field.
func PageIDHasPrefix(v string) predicate.PageView {
	return predicate.PageView(sql.FieldHasPrefix(FieldPageID, v))
}

// PageIDHasSuffix applies the HasSuffix predicate on the "page_id" field.
func PageIDHasSuffix(v string) predicate.PageView {
	return predicate.PageView(sql.FieldHasSuffix(FieldPageID, v))
}

// PageIDEqualFold applies the EqualFold predicate on the "page_id" field.
func PageIDEqualFold(v string) predicate.PageView {
	return predicate.PageView(sql.FieldEqualFold(FieldPageID, v))
}

// PageIDContainsFold applies the ContainsFold predicate on the "page_id" field.
func PageIDContainsFold(v string) predicate.PageView {
	return predicate.PageView(sql.FieldContainsFold(FieldPageID, v))
}

// VisitorIDEQ applies the EQ predicate on the "visitor_id" field.
func VisitorIDEQ(v string) predicate.PageView {
	return predicate.PageView(sql.FieldEQ(FieldVisitorID, v))
}

// VisitorIDNEQ applies the NEQ predicate on the "visitor_id" field.
func VisitorIDNEQ(v string) predicate.PageView {
	return predicate.PageView(sql.FieldNEQ(FieldVisitorID, v))
}

// VisitorIDIn applies the In predicate on the "visitor_id" field.
func VisitorIDIn(vs ...string) predicate.PageView {
	return predicate.PageView(sql.FieldIn(FieldVisitorID, vs...))
}

// VisitorIDNotIn applies the NotIn predicate on the "visitor_id" field.
func VisitorIDNotIn(vs ...string) predicate.PageView {
	return predicate.PageView(sql.FieldNotIn(FieldVisitorID, vs...))
}

// VisitorIDGT applies the GT predicate on the "visitor_id" field.
func VisitorIDGT(v string) predicate.PageView {
	return predicate.PageView(sql.FieldGT(FieldVisitorID, v))
}

// VisitorIDGTE applies the GTE predicate on the "visitor_id" field.
func VisitorIDGTE(v string) predicate.PageView {
	return predicate.PageView(sql.FieldGTE(FieldVisitorID, v))
}

// VisitorIDLT applies the LT predicate on the "visitor_id" field.
func VisitorIDLT(v string) predicate.PageView {
	return predicate.PageView(sql.FieldLT(FieldVisitorID, v))
}

// VisitorIDLTE applies the LTE predicate on the "visitor_id" field.
func VisitorIDLTE(v string) predicate.PageView {
	return predicate.PageView(sql.FieldLTE(FieldVisitorID, v))
}

// VisitorIDContains applies the Contains predicate on the "visitor_id" field.
func VisitorIDContains(v string) predicate.PageView {
	return predicate.PageView(sql.FieldContains(FieldVisitorID, v))
}

// VisitorIDHasPrefix applies the HasPrefix predicate on the "visitor_id" field.
func VisitorIDHasPrefix(v string) predicate.PageView {
	return predicate.PageView(sql.FieldHasPrefix(FieldVisitorID, v))
}

// VisitorIDHasSuffix applies the HasSuffix predicate on the "visitor_id" field.
func VisitorIDHasSuffix(v string) predicate.PageView {
	return predicate.PageView(sql.FieldHasSuffix(FieldVisitorID, v))
}

// VisitorIDEqualFold applies the EqualFold predicate on the "visitor_id" field.
func VisitorIDEqualFold(v string) predicate.PageView {
	return predicate.PageView(sql.FieldEqualFold(FieldVisitorID, v))
}

// VisitorIDContainsFold applies the ContainsFold predicate on the "visitor_id" field.
func VisitorIDContainsFold(v string) predicate.PageView {
	return predicate.PageView(sql.FieldContainsFold(FieldVisitorID, v))
}

// IsAdminEQ applies the EQ predicate on the "is_admin" field.
func IsAdminEQ(v bool) predicate.PageView {
	return predicate.PageView(sql.FieldEQ(FieldIsAdmin, v))
}

// IsAdminNEQ applies the NEQ predicate on the "is_admin" field.
func IsAdminNEQ(v bool) predicate.PageView {
	return predicate.PageView(sql.FieldNEQ(FieldIsAdmin, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PageView {
	return predicate.PageView(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PageView {
	return predicate.PageView(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PageView {
	return predicate.PageView(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PageView {
	return predicate.PageView(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PageView {
	return predicate.PageView(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PageView {
	return predicate.PageView(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PageView {
	return predicate.PageView(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PageView {
	return predicate.PageView(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PageView) predicate.PageView {
	return predicate.PageView(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PageView) predicate.PageView {
	return predicate.PageView(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PageView) predicate.PageView {
	return predicate.PageView(sql.NotPredicates(p))
}
