// Code generated by ent, DO NOT EDIT.

package accountcostconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the accountcostconfig type in the database.
	Label = "account_cost_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldAccountType holds the string denoting the account_type field in the database.
	FieldAccountType = "account_type"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldOauthAccountCost holds the string denoting the oauth_account_cost field in the database.
	FieldOauthAccountCost = "oauth_account_cost"
	// FieldAPIMultiplierOverride holds the string denoting the api_multiplier_override field in the database.
	FieldAPIMultiplierOverride = "api_multiplier_override"
	// FieldSyncedAPIMultiplier holds the string denoting the synced_api_multiplier field in the database.
	FieldSyncedAPIMultiplier = "synced_api_multiplier"
	// FieldAPIMultiplierMode holds the string denoting the api_multiplier_mode field in the database.
	FieldAPIMultiplierMode = "api_multiplier_mode"
	// FieldLastSyncedAt holds the string denoting the last_synced_at field in the database.
	FieldLastSyncedAt = "last_synced_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the accountcostconfig in the database.
	Table = "account_cost_configs"
)

// Columns holds all SQL columns for accountcostconfig fields.
var Columns = []string{
	FieldID,
	FieldAccountID,
	FieldAccountType,
	FieldName,
	FieldPlatform,
	FieldOauthAccountCost,
	FieldAPIMultiplierOverride,
	FieldSyncedAPIMultiplier,
	FieldAPIMultiplierMode,
	FieldLastSyncedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAccountType holds the default value on creation for the "account_type" field.
	DefaultAccountType string
	// AccountTypeValidator is a validator for the "account_type" field. It is called by the builders before save.
	AccountTypeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DefaultAPIMultiplierMode holds the default value on creation for the "api_multiplier_mode" field.
	DefaultAPIMultiplierMode string
	// APIMultiplierModeValidator is a validator for the "api_multiplier_mode" field. It is called by the builders before save.
	APIMultiplierModeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the AccountCostConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByAccountType orders the results by the account_type field.
func ByAccountType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountType, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByOauthAccountCost orders the results by the oauth_account_cost field.
func ByOauthAccountCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOauthAccountCost, opts...).ToFunc()
}

// ByAPIMultiplierOverride orders the results by the api_multiplier_override field.
func ByAPIMultiplierOverride(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIMultiplierOverride, opts...).ToFunc()
}

// BySyncedAPIMultiplier orders the results by the synced_api_multiplier field.
func BySyncedAPIMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncedAPIMultiplier, opts...).ToFunc()
}

// ByAPIMultiplierMode orders the results by the api_multiplier_mode field.
func ByAPIMultiplierMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIMultiplierMode, opts...).ToFunc()
}

// ByLastSyncedAt orders the results by the last_synced_at field.
func ByLastSyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
