// Code generated by ent, DO NOT EDIT.

package accountcostconfig

import (
	"sub2api-extension/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldAccountID, v))
}

// AccountType applies equality check predicate on the "account_type" field. It's identical to AccountTypeEQ.
func AccountType(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldAccountType, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldName, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldPlatform, v))
}

// OauthAccountCost applies equality check predicate on the "oauth_account_cost" field. It's identical to OauthAccountCostEQ.
func OauthAccountCost(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldOauthAccountCost, v))
}

// APIMultiplierOverride applies equality check predicate on the "api_multiplier_override" field. It's identical to APIMultiplierOverrideEQ.
func APIMultiplierOverride(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldAPIMultiplierOverride, v))
}

// SyncedAPIMultiplier applies equality check predicate on the "synced_api_multiplier" field. It's identical to SyncedAPIMultiplierEQ.
func SyncedAPIMultiplier(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldSyncedAPIMultiplier, v))
}

// APIMultiplierMode applies equality check predicate on the "api_multiplier_mode" field. It's identical to APIMultiplierModeEQ.
func APIMultiplierMode(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldAPIMultiplierMode, v))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldLastSyncedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldAccountID, v))
}

// AccountTypeEQ applies the EQ predicate on the "account_type" field.
func AccountTypeEQ(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldAccountType, v))
}

// AccountTypeNEQ applies the NEQ predicate on the "account_type" field.
func AccountTypeNEQ(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldAccountType, v))
}

// AccountTypeIn applies the In predicate on the "account_type" field.
func AccountTypeIn(vs ...string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldAccountType, vs...))
}

// AccountTypeNotIn applies the NotIn predicate on the "account_type" field.
func AccountTypeNotIn(vs ...string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldAccountType, vs...))
}

// AccountTypeGT applies the GT predicate on the "account_type" field.
func AccountTypeGT(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldAccountType, v))
}

// AccountTypeGTE applies the GTE predicate on the "account_type" field.
func AccountTypeGTE(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldAccountType, v))
}

// AccountTypeLT applies the LT predicate on the "account_type" field.
func AccountTypeLT(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldAccountType, v))
}

// AccountTypeLTE applies the LTE predicate on the "account_type" field.
func AccountTypeLTE(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldAccountType, v))
}

// AccountTypeContains applies the Contains predicate on the "account_type" field.
func AccountTypeContains(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldContains(FieldAccountType, v))
}

// AccountTypeHasPrefix applies the HasPrefix predicate on the "account_type" field.
func AccountTypeHasPrefix(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldHasPrefix(FieldAccountType, v))
}

// AccountTypeHasSuffix applies the HasSuffix predicate on the "account_type" field.
func AccountTypeHasSuffix(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldHasSuffix(FieldAccountType, v))
}

// AccountTypeEqualFold applies the EqualFold predicate on the "account_type" field.
func AccountTypeEqualFold(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEqualFold(FieldAccountType, v))
}

// AccountTypeContainsFold applies the ContainsFold predicate on the "account_type" field.
func AccountTypeContainsFold(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldContainsFold(FieldAccountType, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldContainsFold(FieldName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformIsNil applies the IsNil predicate on the "platform" field.
func PlatformIsNil() predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIsNull(FieldPlatform))
}

// PlatformNotNil applies the NotNil predicate on the "platform" field.
func PlatformNotNil() predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotNull(FieldPlatform))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldContainsFold(FieldPlatform, v))
}

// OauthAccountCostEQ applies the EQ predicate on the "oauth_account_cost" field.
func OauthAccountCostEQ(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldOauthAccountCost, v))
}

// OauthAccountCostNEQ applies the NEQ predicate on the "oauth_account_cost" field.
func OauthAccountCostNEQ(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldOauthAccountCost, v))
}

// OauthAccountCostIn applies the In predicate on the "oauth_account_cost" field.
func OauthAccountCostIn(vs ...float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldOauthAccountCost, vs...))
}

// OauthAccountCostNotIn applies the NotIn predicate on the "oauth_account_cost" field.
func OauthAccountCostNotIn(vs ...float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldOauthAccountCost, vs...))
}

// OauthAccountCostGT applies the GT predicate on the "oauth_account_cost" field.
func OauthAccountCostGT(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldOauthAccountCost, v))
}

// OauthAccountCostGTE applies the GTE predicate on the "oauth_account_cost" field.
func OauthAccountCostGTE(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldOauthAccountCost, v))
}

// OauthAccountCostLT applies the LT predicate on the "oauth_account_cost" field.
func OauthAccountCostLT(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldOauthAccountCost, v))
}

// OauthAccountCostLTE applies the LTE predicate on the "oauth_account_cost" field.
func OauthAccountCostLTE(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldOauthAccountCost, v))
}

// OauthAccountCostIsNil applies the IsNil predicate on the "oauth_account_cost" field.
func OauthAccountCostIsNil() predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIsNull(FieldOauthAccountCost))
}

// OauthAccountCostNotNil applies the NotNil predicate on the "oauth_account_cost" field.
func OauthAccountCostNotNil() predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotNull(FieldOauthAccountCost))
}

// APIMultiplierOverrideEQ applies the EQ predicate on the "api_multiplier_override" field.
func APIMultiplierOverrideEQ(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldAPIMultiplierOverride, v))
}

// APIMultiplierOverrideNEQ applies the NEQ predicate on the "api_multiplier_override" field.
func APIMultiplierOverrideNEQ(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldAPIMultiplierOverride, v))
}

// APIMultiplierOverrideIn applies the In predicate on the "api_multiplier_override" field.
func APIMultiplierOverrideIn(vs ...float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldAPIMultiplierOverride, vs...))
}

// APIMultiplierOverrideNotIn applies the NotIn predicate on the "api_multiplier_override" field.
func APIMultiplierOverrideNotIn(vs ...float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldAPIMultiplierOverride, vs...))
}

// APIMultiplierOverrideGT applies the GT predicate on the "api_multiplier_override" field.
func APIMultiplierOverrideGT(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldAPIMultiplierOverride, v))
}

// APIMultiplierOverrideGTE applies the GTE predicate on the "api_multiplier_override" field.
func APIMultiplierOverrideGTE(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldAPIMultiplierOverride, v))
}

// APIMultiplierOverrideLT applies the LT predicate on the "api_multiplier_override" field.
func APIMultiplierOverrideLT(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldAPIMultiplierOverride, v))
}

// APIMultiplierOverrideLTE applies the LTE predicate on the "api_multiplier_override" field.
func APIMultiplierOverrideLTE(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldAPIMultiplierOverride, v))
}

// APIMultiplierOverrideIsNil applies the IsNil predicate on the "api_multiplier_override" field.
func APIMultiplierOverrideIsNil() predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIsNull(FieldAPIMultiplierOverride))
}

// APIMultiplierOverrideNotNil applies the NotNil predicate on the "api_multiplier_override" field.
func APIMultiplierOverrideNotNil() predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotNull(FieldAPIMultiplierOverride))
}

// SyncedAPIMultiplierEQ applies the EQ predicate on the "synced_api_multiplier" field.
func SyncedAPIMultiplierEQ(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldSyncedAPIMultiplier, v))
}

// SyncedAPIMultiplierNEQ applies the NEQ predicate on the "synced_api_multiplier" field.
func SyncedAPIMultiplierNEQ(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldSyncedAPIMultiplier, v))
}

// SyncedAPIMultiplierIn applies the In predicate on the "synced_api_multiplier" field.
func SyncedAPIMultiplierIn(vs ...float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldSyncedAPIMultiplier, vs...))
}

// SyncedAPIMultiplierNotIn applies the NotIn predicate on the "synced_api_multiplier" field.
func SyncedAPIMultiplierNotIn(vs ...float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldSyncedAPIMultiplier, vs...))
}

// SyncedAPIMultiplierGT applies the GT predicate on the "synced_api_multiplier" field.
func SyncedAPIMultiplierGT(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldSyncedAPIMultiplier, v))
}

// SyncedAPIMultiplierGTE applies the GTE predicate on the "synced_api_multiplier" field.
func SyncedAPIMultiplierGTE(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldSyncedAPIMultiplier, v))
}

// SyncedAPIMultiplierLT applies the LT predicate on the "synced_api_multiplier" field.
func SyncedAPIMultiplierLT(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldSyncedAPIMultiplier, v))
}

// SyncedAPIMultiplierLTE applies the LTE predicate on the "synced_api_multiplier" field.
func SyncedAPIMultiplierLTE(v float64) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldSyncedAPIMultiplier, v))
}

// SyncedAPIMultiplierIsNil applies the IsNil predicate on the "synced_api_multiplier" field.
func SyncedAPIMultiplierIsNil() predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIsNull(FieldSyncedAPIMultiplier))
}

// SyncedAPIMultiplierNotNil applies the NotNil predicate on the "synced_api_multiplier" field.
func SyncedAPIMultiplierNotNil() predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotNull(FieldSyncedAPIMultiplier))
}

// APIMultiplierModeEQ applies the EQ predicate on the "api_multiplier_mode" field.
func APIMultiplierModeEQ(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldAPIMultiplierMode, v))
}

// APIMultiplierModeNEQ applies the NEQ predicate on the "api_multiplier_mode" field.
func APIMultiplierModeNEQ(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldAPIMultiplierMode, v))
}

// APIMultiplierModeIn applies the In predicate on the "api_multiplier_mode" field.
func APIMultiplierModeIn(vs ...string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldAPIMultiplierMode, vs...))
}

// APIMultiplierModeNotIn applies the NotIn predicate on the "api_multiplier_mode" field.
func APIMultiplierModeNotIn(vs ...string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldAPIMultiplierMode, vs...))
}

// APIMultiplierModeGT applies the GT predicate on the "api_multiplier_mode" field.
func APIMultiplierModeGT(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldAPIMultiplierMode, v))
}

// APIMultiplierModeGTE applies the GTE predicate on the "api_multiplier_mode" field.
func APIMultiplierModeGTE(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldAPIMultiplierMode, v))
}

// APIMultiplierModeLT applies the LT predicate on the "api_multiplier_mode" field.
func APIMultiplierModeLT(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldAPIMultiplierMode, v))
}

// APIMultiplierModeLTE applies the LTE predicate on the "api_multiplier_mode" field.
func APIMultiplierModeLTE(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldAPIMultiplierMode, v))
}

// APIMultiplierModeContains applies the Contains predicate on the "api_multiplier_mode" field.
func APIMultiplierModeContains(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldContains(FieldAPIMultiplierMode, v))
}

// APIMultiplierModeHasPrefix applies the HasPrefix predicate on the "api_multiplier_mode" field.
func APIMultiplierModeHasPrefix(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldHasPrefix(FieldAPIMultiplierMode, v))
}

// APIMultiplierModeHasSuffix applies the HasSuffix predicate on the "api_multiplier_mode" field.
func APIMultiplierModeHasSuffix(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldHasSuffix(FieldAPIMultiplierMode, v))
}

// APIMultiplierModeEqualFold applies the EqualFold predicate on the "api_multiplier_mode" field.
func APIMultiplierModeEqualFold(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEqualFold(FieldAPIMultiplierMode, v))
}

// APIMultiplierModeContainsFold applies the ContainsFold predicate on the "api_multiplier_mode" field.
func APIMultiplierModeContainsFold(v string) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldContainsFold(FieldAPIMultiplierMode, v))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldLastSyncedAt, v))
}

// LastSyncedAtIsNil applies the IsNil predicate on the "last_synced_at" field.
func LastSyncedAtIsNil() predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIsNull(FieldLastSyncedAt))
}

// LastSyncedAtNotNil applies the NotNil predicate on the "last_synced_at" field.
func LastSyncedAtNotNil() predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotNull(FieldLastSyncedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountCostConfig) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountCostConfig) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountCostConfig) predicate.AccountCostConfig {
	return predicate.AccountCostConfig(sql.NotPredicates(p))
}
