// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"sub2api-extension/ent/migrate"

	"sub2api-extension/ent/featureclick"
	"sub2api-extension/ent/imageasset"
	"sub2api-extension/ent/invoiceorder"
	"sub2api-extension/ent/invoiceprofile"
	"sub2api-extension/ent/invoicerequest"
	"sub2api-extension/ent/page"
	"sub2api-extension/ent/pageview"
	"sub2api-extension/ent/systemmeta"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// FeatureClick is the client for interacting with the FeatureClick builders.
	FeatureClick *FeatureClickClient
	// ImageAsset is the client for interacting with the ImageAsset builders.
	ImageAsset *ImageAssetClient
	// InvoiceOrder is the client for interacting with the InvoiceOrder builders.
	InvoiceOrder *InvoiceOrderClient
	// InvoiceProfile is the client for interacting with the InvoiceProfile builders.
	InvoiceProfile *InvoiceProfileClient
	// InvoiceRequest is the client for interacting with the InvoiceRequest builders.
	InvoiceRequest *InvoiceRequestClient
	// Page is the client for interacting with the Page builders.
	Page *PageClient
	// PageView is the client for interacting with the PageView builders.
	PageView *PageViewClient
	// SystemMeta is the client for interacting with the SystemMeta builders.
	SystemMeta *SystemMetaClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.FeatureClick = NewFeatureClickClient(c.config)
	c.ImageAsset = NewImageAssetClient(c.config)
	c.InvoiceOrder = NewInvoiceOrderClient(c.config)
	c.InvoiceProfile = NewInvoiceProfileClient(c.config)
	c.InvoiceRequest = NewInvoiceRequestClient(c.config)
	c.Page = NewPageClient(c.config)
	c.PageView = NewPageViewClient(c.config)
	c.SystemMeta = NewSystemMetaClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		FeatureClick:   NewFeatureClickClient(cfg),
		ImageAsset:     NewImageAssetClient(cfg),
		InvoiceOrder:   NewInvoiceOrderClient(cfg),
		InvoiceProfile: NewInvoiceProfileClient(cfg),
		InvoiceRequest: NewInvoiceRequestClient(cfg),
		Page:           NewPageClient(cfg),
		PageView:       NewPageViewClient(cfg),
		SystemMeta:     NewSystemMetaClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		FeatureClick:   NewFeatureClickClient(cfg),
		ImageAsset:     NewImageAssetClient(cfg),
		InvoiceOrder:   NewInvoiceOrderClient(cfg),
		InvoiceProfile: NewInvoiceProfileClient(cfg),
		InvoiceRequest: NewInvoiceRequestClient(cfg),
		Page:           NewPageClient(cfg),
		PageView:       NewPageViewClient(cfg),
		SystemMeta:     NewSystemMetaClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		FeatureClick.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.FeatureClick, c.ImageAsset, c.InvoiceOrder, c.InvoiceProfile,
		c.InvoiceRequest, c.Page, c.PageView, c.SystemMeta,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.FeatureClick, c.ImageAsset, c.InvoiceOrder, c.InvoiceProfile,
		c.InvoiceRequest, c.Page, c.PageView, c.SystemMeta,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *FeatureClickMutation:
		return c.FeatureClick.mutate(ctx, m)
	case *ImageAssetMutation:
		return c.ImageAsset.mutate(ctx, m)
	case *InvoiceOrderMutation:
		return c.InvoiceOrder.mutate(ctx, m)
	case *InvoiceProfileMutation:
		return c.InvoiceProfile.mutate(ctx, m)
	case *InvoiceRequestMutation:
		return c.InvoiceRequest.mutate(ctx, m)
	case *PageMutation:
		return c.Page.mutate(ctx, m)
	case *PageViewMutation:
		return c.PageView.mutate(ctx, m)
	case *SystemMetaMutation:
		return c.SystemMeta.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// FeatureClickClient is a client for the FeatureClick schema.
type FeatureClickClient struct {
	config
}

// NewFeatureClickClient returns a client for the FeatureClick from the given config.
func NewFeatureClickClient(c config) *FeatureClickClient {
	return &FeatureClickClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `featureclick.Hooks(f(g(h())))`.
func (c *FeatureClickClient) Use(hooks ...Hook) {
	c.hooks.FeatureClick = append(c.hooks.FeatureClick, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `featureclick.Intercept(f(g(h())))`.
func (c *FeatureClickClient) Intercept(interceptors ...Interceptor) {
	c.inters.FeatureClick = append(c.inters.FeatureClick, interceptors...)
}

// Create returns a builder for creating a FeatureClick entity.
func (c *FeatureClickClient) Create() *FeatureClickCreate {
	mutation := newFeatureClickMutation(c.config, OpCreate)
	return &FeatureClickCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FeatureClick entities.
func (c *FeatureClickClient) CreateBulk(builders ...*FeatureClickCreate) *FeatureClickCreateBulk {
	return &FeatureClickCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FeatureClickClient) MapCreateBulk(slice any, setFunc func(*FeatureClickCreate, int)) *FeatureClickCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FeatureClickCreateBulk{err: fmt.Errorf("calling to FeatureClickClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FeatureClickCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FeatureClickCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FeatureClick.
func (c *FeatureClickClient) Update() *FeatureClickUpdate {
	mutation := newFeatureClickMutation(c.config, OpUpdate)
	return &FeatureClickUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FeatureClickClient) UpdateOne(_m *FeatureClick) *FeatureClickUpdateOne {
	mutation := newFeatureClickMutation(c.config, OpUpdateOne, withFeatureClick(_m))
	return &FeatureClickUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FeatureClickClient) UpdateOneID(id int) *FeatureClickUpdateOne {
	mutation := newFeatureClickMutation(c.config, OpUpdateOne, withFeatureClickID(id))
	return &FeatureClickUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FeatureClick.
func (c *FeatureClickClient) Delete() *FeatureClickDelete {
	mutation := newFeatureClickMutation(c.config, OpDelete)
	return &FeatureClickDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FeatureClickClient) DeleteOne(_m *FeatureClick) *FeatureClickDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FeatureClickClient) DeleteOneID(id int) *FeatureClickDeleteOne {
	builder := c.Delete().Where(featureclick.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FeatureClickDeleteOne{builder}
}

// Query returns a query builder for FeatureClick.
func (c *FeatureClickClient) Query() *FeatureClickQuery {
	return &FeatureClickQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFeatureClick},
		inters: c.Interceptors(),
	}
}

// Get returns a FeatureClick entity by its id.
func (c *FeatureClickClient) Get(ctx context.Context, id int) (*FeatureClick, error) {
	return c.Query().Where(featureclick.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FeatureClickClient) GetX(ctx context.Context, id int) *FeatureClick {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FeatureClickClient) Hooks() []Hook {
	return c.hooks.FeatureClick
}

// Interceptors returns the client interceptors.
func (c *FeatureClickClient) Interceptors() []Interceptor {
	return c.inters.FeatureClick
}

func (c *FeatureClickClient) mutate(ctx context.Context, m *FeatureClickMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FeatureClickCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FeatureClickUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FeatureClickUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FeatureClickDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown FeatureClick mutation op: %q", m.Op())
	}
}

// ImageAssetClient is a client for the ImageAsset schema.
type ImageAssetClient struct {
	config
}

// NewImageAssetClient returns a client for the ImageAsset from the given config.
func NewImageAssetClient(c config) *ImageAssetClient {
	return &ImageAssetClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `imageasset.Hooks(f(g(h())))`.
func (c *ImageAssetClient) Use(hooks ...Hook) {
	c.hooks.ImageAsset = append(c.hooks.ImageAsset, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `imageasset.Intercept(f(g(h())))`.
func (c *ImageAssetClient) Intercept(interceptors ...Interceptor) {
	c.inters.ImageAsset = append(c.inters.ImageAsset, interceptors...)
}

// Create returns a builder for creating a ImageAsset entity.
func (c *ImageAssetClient) Create() *ImageAssetCreate {
	mutation := newImageAssetMutation(c.config, OpCreate)
	return &ImageAssetCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ImageAsset entities.
func (c *ImageAssetClient) CreateBulk(builders ...*ImageAssetCreate) *ImageAssetCreateBulk {
	return &ImageAssetCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ImageAssetClient) MapCreateBulk(slice any, setFunc func(*ImageAssetCreate, int)) *ImageAssetCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ImageAssetCreateBulk{err: fmt.Errorf("calling to ImageAssetClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ImageAssetCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ImageAssetCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ImageAsset.
func (c *ImageAssetClient) Update() *ImageAssetUpdate {
	mutation := newImageAssetMutation(c.config, OpUpdate)
	return &ImageAssetUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ImageAssetClient) UpdateOne(_m *ImageAsset) *ImageAssetUpdateOne {
	mutation := newImageAssetMutation(c.config, OpUpdateOne, withImageAsset(_m))
	return &ImageAssetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ImageAssetClient) UpdateOneID(id int) *ImageAssetUpdateOne {
	mutation := newImageAssetMutation(c.config, OpUpdateOne, withImageAssetID(id))
	return &ImageAssetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ImageAsset.
func (c *ImageAssetClient) Delete() *ImageAssetDelete {
	mutation := newImageAssetMutation(c.config, OpDelete)
	return &ImageAssetDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ImageAssetClient) DeleteOne(_m *ImageAsset) *ImageAssetDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ImageAssetClient) DeleteOneID(id int) *ImageAssetDeleteOne {
	builder := c.Delete().Where(imageasset.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ImageAssetDeleteOne{builder}
}

// Query returns a query builder for ImageAsset.
func (c *ImageAssetClient) Query() *ImageAssetQuery {
	return &ImageAssetQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeImageAsset},
		inters: c.Interceptors(),
	}
}

// Get returns a ImageAsset entity by its id.
func (c *ImageAssetClient) Get(ctx context.Context, id int) (*ImageAsset, error) {
	return c.Query().Where(imageasset.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ImageAssetClient) GetX(ctx context.Context, id int) *ImageAsset {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ImageAssetClient) Hooks() []Hook {
	return c.hooks.ImageAsset
}

// Interceptors returns the client interceptors.
func (c *ImageAssetClient) Interceptors() []Interceptor {
	return c.inters.ImageAsset
}

func (c *ImageAssetClient) mutate(ctx context.Context, m *ImageAssetMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ImageAssetCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ImageAssetUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ImageAssetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ImageAssetDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ImageAsset mutation op: %q", m.Op())
	}
}

// InvoiceOrderClient is a client for the InvoiceOrder schema.
type InvoiceOrderClient struct {
	config
}

// NewInvoiceOrderClient returns a client for the InvoiceOrder from the given config.
func NewInvoiceOrderClient(c config) *InvoiceOrderClient {
	return &InvoiceOrderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `invoiceorder.Hooks(f(g(h())))`.
func (c *InvoiceOrderClient) Use(hooks ...Hook) {
	c.hooks.InvoiceOrder = append(c.hooks.InvoiceOrder, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `invoiceorder.Intercept(f(g(h())))`.
func (c *InvoiceOrderClient) Intercept(interceptors ...Interceptor) {
	c.inters.InvoiceOrder = append(c.inters.InvoiceOrder, interceptors...)
}

// Create returns a builder for creating a InvoiceOrder entity.
func (c *InvoiceOrderClient) Create() *InvoiceOrderCreate {
	mutation := newInvoiceOrderMutation(c.config, OpCreate)
	return &InvoiceOrderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of InvoiceOrder entities.
func (c *InvoiceOrderClient) CreateBulk(builders ...*InvoiceOrderCreate) *InvoiceOrderCreateBulk {
	return &InvoiceOrderCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *InvoiceOrderClient) MapCreateBulk(slice any, setFunc func(*InvoiceOrderCreate, int)) *InvoiceOrderCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &InvoiceOrderCreateBulk{err: fmt.Errorf("calling to InvoiceOrderClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*InvoiceOrderCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &InvoiceOrderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for InvoiceOrder.
func (c *InvoiceOrderClient) Update() *InvoiceOrderUpdate {
	mutation := newInvoiceOrderMutation(c.config, OpUpdate)
	return &InvoiceOrderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InvoiceOrderClient) UpdateOne(_m *InvoiceOrder) *InvoiceOrderUpdateOne {
	mutation := newInvoiceOrderMutation(c.config, OpUpdateOne, withInvoiceOrder(_m))
	return &InvoiceOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InvoiceOrderClient) UpdateOneID(id int) *InvoiceOrderUpdateOne {
	mutation := newInvoiceOrderMutation(c.config, OpUpdateOne, withInvoiceOrderID(id))
	return &InvoiceOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for InvoiceOrder.
func (c *InvoiceOrderClient) Delete() *InvoiceOrderDelete {
	mutation := newInvoiceOrderMutation(c.config, OpDelete)
	return &InvoiceOrderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InvoiceOrderClient) DeleteOne(_m *InvoiceOrder) *InvoiceOrderDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InvoiceOrderClient) DeleteOneID(id int) *InvoiceOrderDeleteOne {
	builder := c.Delete().Where(invoiceorder.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InvoiceOrderDeleteOne{builder}
}

// Query returns a query builder for InvoiceOrder.
func (c *InvoiceOrderClient) Query() *InvoiceOrderQuery {
	return &InvoiceOrderQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInvoiceOrder},
		inters: c.Interceptors(),
	}
}

// Get returns a InvoiceOrder entity by its id.
func (c *InvoiceOrderClient) Get(ctx context.Context, id int) (*InvoiceOrder, error) {
	return c.Query().Where(invoiceorder.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InvoiceOrderClient) GetX(ctx context.Context, id int) *InvoiceOrder {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *InvoiceOrderClient) Hooks() []Hook {
	return c.hooks.InvoiceOrder
}

// Interceptors returns the client interceptors.
func (c *InvoiceOrderClient) Interceptors() []Interceptor {
	return c.inters.InvoiceOrder
}

func (c *InvoiceOrderClient) mutate(ctx context.Context, m *InvoiceOrderMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InvoiceOrderCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InvoiceOrderUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InvoiceOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InvoiceOrderDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown InvoiceOrder mutation op: %q", m.Op())
	}
}

// InvoiceProfileClient is a client for the InvoiceProfile schema.
type InvoiceProfileClient struct {
	config
}

// NewInvoiceProfileClient returns a client for the InvoiceProfile from the given config.
func NewInvoiceProfileClient(c config) *InvoiceProfileClient {
	return &InvoiceProfileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `invoiceprofile.Hooks(f(g(h())))`.
func (c *InvoiceProfileClient) Use(hooks ...Hook) {
	c.hooks.InvoiceProfile = append(c.hooks.InvoiceProfile, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `invoiceprofile.Intercept(f(g(h())))`.
func (c *InvoiceProfileClient) Intercept(interceptors ...Interceptor) {
	c.inters.InvoiceProfile = append(c.inters.InvoiceProfile, interceptors...)
}

// Create returns a builder for creating a InvoiceProfile entity.
func (c *InvoiceProfileClient) Create() *InvoiceProfileCreate {
	mutation := newInvoiceProfileMutation(c.config, OpCreate)
	return &InvoiceProfileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of InvoiceProfile entities.
func (c *InvoiceProfileClient) CreateBulk(builders ...*InvoiceProfileCreate) *InvoiceProfileCreateBulk {
	return &InvoiceProfileCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *InvoiceProfileClient) MapCreateBulk(slice any, setFunc func(*InvoiceProfileCreate, int)) *InvoiceProfileCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &InvoiceProfileCreateBulk{err: fmt.Errorf("calling to InvoiceProfileClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*InvoiceProfileCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &InvoiceProfileCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for InvoiceProfile.
func (c *InvoiceProfileClient) Update() *InvoiceProfileUpdate {
	mutation := newInvoiceProfileMutation(c.config, OpUpdate)
	return &InvoiceProfileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InvoiceProfileClient) UpdateOne(_m *InvoiceProfile) *InvoiceProfileUpdateOne {
	mutation := newInvoiceProfileMutation(c.config, OpUpdateOne, withInvoiceProfile(_m))
	return &InvoiceProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InvoiceProfileClient) UpdateOneID(id int) *InvoiceProfileUpdateOne {
	mutation := newInvoiceProfileMutation(c.config, OpUpdateOne, withInvoiceProfileID(id))
	return &InvoiceProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for InvoiceProfile.
func (c *InvoiceProfileClient) Delete() *InvoiceProfileDelete {
	mutation := newInvoiceProfileMutation(c.config, OpDelete)
	return &InvoiceProfileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InvoiceProfileClient) DeleteOne(_m *InvoiceProfile) *InvoiceProfileDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InvoiceProfileClient) DeleteOneID(id int) *InvoiceProfileDeleteOne {
	builder := c.Delete().Where(invoiceprofile.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InvoiceProfileDeleteOne{builder}
}

// Query returns a query builder for InvoiceProfile.
func (c *InvoiceProfileClient) Query() *InvoiceProfileQuery {
	return &InvoiceProfileQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInvoiceProfile},
		inters: c.Interceptors(),
	}
}

// Get returns a InvoiceProfile entity by its id.
func (c *InvoiceProfileClient) Get(ctx context.Context, id int) (*InvoiceProfile, error) {
	return c.Query().Where(invoiceprofile.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InvoiceProfileClient) GetX(ctx context.Context, id int) *InvoiceProfile {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *InvoiceProfileClient) Hooks() []Hook {
	return c.hooks.InvoiceProfile
}

// Interceptors returns the client interceptors.
func (c *InvoiceProfileClient) Interceptors() []Interceptor {
	return c.inters.InvoiceProfile
}

func (c *InvoiceProfileClient) mutate(ctx context.Context, m *InvoiceProfileMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InvoiceProfileCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InvoiceProfileUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InvoiceProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InvoiceProfileDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown InvoiceProfile mutation op: %q", m.Op())
	}
}

// InvoiceRequestClient is a client for the InvoiceRequest schema.
type InvoiceRequestClient struct {
	config
}

// NewInvoiceRequestClient returns a client for the InvoiceRequest from the given config.
func NewInvoiceRequestClient(c config) *InvoiceRequestClient {
	return &InvoiceRequestClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `invoicerequest.Hooks(f(g(h())))`.
func (c *InvoiceRequestClient) Use(hooks ...Hook) {
	c.hooks.InvoiceRequest = append(c.hooks.InvoiceRequest, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `invoicerequest.Intercept(f(g(h())))`.
func (c *InvoiceRequestClient) Intercept(interceptors ...Interceptor) {
	c.inters.InvoiceRequest = append(c.inters.InvoiceRequest, interceptors...)
}

// Create returns a builder for creating a InvoiceRequest entity.
func (c *InvoiceRequestClient) Create() *InvoiceRequestCreate {
	mutation := newInvoiceRequestMutation(c.config, OpCreate)
	return &InvoiceRequestCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of InvoiceRequest entities.
func (c *InvoiceRequestClient) CreateBulk(builders ...*InvoiceRequestCreate) *InvoiceRequestCreateBulk {
	return &InvoiceRequestCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *InvoiceRequestClient) MapCreateBulk(slice any, setFunc func(*InvoiceRequestCreate, int)) *InvoiceRequestCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &InvoiceRequestCreateBulk{err: fmt.Errorf("calling to InvoiceRequestClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*InvoiceRequestCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &InvoiceRequestCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for InvoiceRequest.
func (c *InvoiceRequestClient) Update() *InvoiceRequestUpdate {
	mutation := newInvoiceRequestMutation(c.config, OpUpdate)
	return &InvoiceRequestUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InvoiceRequestClient) UpdateOne(_m *InvoiceRequest) *InvoiceRequestUpdateOne {
	mutation := newInvoiceRequestMutation(c.config, OpUpdateOne, withInvoiceRequest(_m))
	return &InvoiceRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InvoiceRequestClient) UpdateOneID(id int) *InvoiceRequestUpdateOne {
	mutation := newInvoiceRequestMutation(c.config, OpUpdateOne, withInvoiceRequestID(id))
	return &InvoiceRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for InvoiceRequest.
func (c *InvoiceRequestClient) Delete() *InvoiceRequestDelete {
	mutation := newInvoiceRequestMutation(c.config, OpDelete)
	return &InvoiceRequestDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InvoiceRequestClient) DeleteOne(_m *InvoiceRequest) *InvoiceRequestDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InvoiceRequestClient) DeleteOneID(id int) *InvoiceRequestDeleteOne {
	builder := c.Delete().Where(invoicerequest.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InvoiceRequestDeleteOne{builder}
}

// Query returns a query builder for InvoiceRequest.
func (c *InvoiceRequestClient) Query() *InvoiceRequestQuery {
	return &InvoiceRequestQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInvoiceRequest},
		inters: c.Interceptors(),
	}
}

// Get returns a InvoiceRequest entity by its id.
func (c *InvoiceRequestClient) Get(ctx context.Context, id int) (*InvoiceRequest, error) {
	return c.Query().Where(invoicerequest.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InvoiceRequestClient) GetX(ctx context.Context, id int) *InvoiceRequest {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *InvoiceRequestClient) Hooks() []Hook {
	return c.hooks.InvoiceRequest
}

// Interceptors returns the client interceptors.
func (c *InvoiceRequestClient) Interceptors() []Interceptor {
	return c.inters.InvoiceRequest
}

func (c *InvoiceRequestClient) mutate(ctx context.Context, m *InvoiceRequestMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InvoiceRequestCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InvoiceRequestUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InvoiceRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InvoiceRequestDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown InvoiceRequest mutation op: %q", m.Op())
	}
}

// PageClient is a client for the Page schema.
type PageClient struct {
	config
}

// NewPageClient returns a client for the Page from the given config.
func NewPageClient(c config) *PageClient {
	return &PageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `page.Hooks(f(g(h())))`.
func (c *PageClient) Use(hooks ...Hook) {
	c.hooks.Page = append(c.hooks.Page, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `page.Intercept(f(g(h())))`.
func (c *PageClient) Intercept(interceptors ...Interceptor) {
	c.inters.Page = append(c.inters.Page, interceptors...)
}

// Create returns a builder for creating a Page entity.
func (c *PageClient) Create() *PageCreate {
	mutation := newPageMutation(c.config, OpCreate)
	return &PageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Page entities.
func (c *PageClient) CreateBulk(builders ...*PageCreate) *PageCreateBulk {
	return &PageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PageClient) MapCreateBulk(slice any, setFunc func(*PageCreate, int)) *PageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PageCreateBulk{err: fmt.Errorf("calling to PageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Page.
func (c *PageClient) Update() *PageUpdate {
	mutation := newPageMutation(c.config, OpUpdate)
	return &PageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PageClient) UpdateOne(_m *Page) *PageUpdateOne {
	mutation := newPageMutation(c.config, OpUpdateOne, withPage(_m))
	return &PageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PageClient) UpdateOneID(id int) *PageUpdateOne {
	mutation := newPageMutation(c.config, OpUpdateOne, withPageID(id))
	return &PageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Page.
func (c *PageClient) Delete() *PageDelete {
	mutation := newPageMutation(c.config, OpDelete)
	return &PageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PageClient) DeleteOne(_m *Page) *PageDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PageClient) DeleteOneID(id int) *PageDeleteOne {
	builder := c.Delete().Where(page.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PageDeleteOne{builder}
}

// Query returns a query builder for Page.
func (c *PageClient) Query() *PageQuery {
	return &PageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePage},
		inters: c.Interceptors(),
	}
}

// Get returns a Page entity by its id.
func (c *PageClient) Get(ctx context.Context, id int) (*Page, error) {
	return c.Query().Where(page.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PageClient) GetX(ctx context.Context, id int) *Page {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PageClient) Hooks() []Hook {
	return c.hooks.Page
}

// Interceptors returns the client interceptors.
func (c *PageClient) Interceptors() []Interceptor {
	return c.inters.Page
}

func (c *PageClient) mutate(ctx context.Context, m *PageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Page mutation op: %q", m.Op())
	}
}

// PageViewClient is a client for the PageView schema.
type PageViewClient struct {
	config
}

// NewPageViewClient returns a client for the PageView from the given config.
func NewPageViewClient(c config) *PageViewClient {
	return &PageViewClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pageview.Hooks(f(g(h())))`.
func (c *PageViewClient) Use(hooks ...Hook) {
	c.hooks.PageView = append(c.hooks.PageView, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pageview.Intercept(f(g(h())))`.
func (c *PageViewClient) Intercept(interceptors ...Interceptor) {
	c.inters.PageView = append(c.inters.PageView, interceptors...)
}

// Create returns a builder for creating a PageView entity.
func (c *PageViewClient) Create() *PageViewCreate {
	mutation := newPageViewMutation(c.config, OpCreate)
	return &PageViewCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PageView entities.
func (c *PageViewClient) CreateBulk(builders ...*PageViewCreate) *PageViewCreateBulk {
	return &PageViewCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PageViewClient) MapCreateBulk(slice any, setFunc func(*PageViewCreate, int)) *PageViewCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PageViewCreateBulk{err: fmt.Errorf("calling to PageViewClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PageViewCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PageViewCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PageView.
func (c *PageViewClient) Update() *PageViewUpdate {
	mutation := newPageViewMutation(c.config, OpUpdate)
	return &PageViewUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PageViewClient) UpdateOne(_m *PageView) *PageViewUpdateOne {
	mutation := newPageViewMutation(c.config, OpUpdateOne, withPageView(_m))
	return &PageViewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PageViewClient) UpdateOneID(id int) *PageViewUpdateOne {
	mutation := newPageViewMutation(c.config, OpUpdateOne, withPageViewID(id))
	return &PageViewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PageView.
func (c *PageViewClient) Delete() *PageViewDelete {
	mutation := newPageViewMutation(c.config, OpDelete)
	return &PageViewDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PageViewClient) DeleteOne(_m *PageView) *PageViewDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PageViewClient) DeleteOneID(id int) *PageViewDeleteOne {
	builder := c.Delete().Where(pageview.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PageViewDeleteOne{builder}
}

// Query returns a query builder for PageView.
func (c *PageViewClient) Query() *PageViewQuery {
	return &PageViewQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePageView},
		inters: c.Interceptors(),
	}
}

// Get returns a PageView entity by its id.
func (c *PageViewClient) Get(ctx context.Context, id int) (*PageView, error) {
	return c.Query().Where(pageview.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PageViewClient) GetX(ctx context.Context, id int) *PageView {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PageViewClient) Hooks() []Hook {
	return c.hooks.PageView
}

// Interceptors returns the client interceptors.
func (c *PageViewClient) Interceptors() []Interceptor {
	return c.inters.PageView
}

func (c *PageViewClient) mutate(ctx context.Context, m *PageViewMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PageViewCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PageViewUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PageViewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PageViewDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PageView mutation op: %q", m.Op())
	}
}

// SystemMetaClient is a client for the SystemMeta schema.
type SystemMetaClient struct {
	config
}

// NewSystemMetaClient returns a client for the SystemMeta from the given config.
func NewSystemMetaClient(c config) *SystemMetaClient {
	return &SystemMetaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `systemmeta.Hooks(f(g(h())))`.
func (c *SystemMetaClient) Use(hooks ...Hook) {
	c.hooks.SystemMeta = append(c.hooks.SystemMeta, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `systemmeta.Intercept(f(g(h())))`.
func (c *SystemMetaClient) Intercept(interceptors ...Interceptor) {
	c.inters.SystemMeta = append(c.inters.SystemMeta, interceptors...)
}

// Create returns a builder for creating a SystemMeta entity.
func (c *SystemMetaClient) Create() *SystemMetaCreate {
	mutation := newSystemMetaMutation(c.config, OpCreate)
	return &SystemMetaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SystemMeta entities.
func (c *SystemMetaClient) CreateBulk(builders ...*SystemMetaCreate) *SystemMetaCreateBulk {
	return &SystemMetaCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SystemMetaClient) MapCreateBulk(slice any, setFunc func(*SystemMetaCreate, int)) *SystemMetaCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SystemMetaCreateBulk{err: fmt.Errorf("calling to SystemMetaClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SystemMetaCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SystemMetaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SystemMeta.
func (c *SystemMetaClient) Update() *SystemMetaUpdate {
	mutation := newSystemMetaMutation(c.config, OpUpdate)
	return &SystemMetaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SystemMetaClient) UpdateOne(_m *SystemMeta) *SystemMetaUpdateOne {
	mutation := newSystemMetaMutation(c.config, OpUpdateOne, withSystemMeta(_m))
	return &SystemMetaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SystemMetaClient) UpdateOneID(id int) *SystemMetaUpdateOne {
	mutation := newSystemMetaMutation(c.config, OpUpdateOne, withSystemMetaID(id))
	return &SystemMetaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SystemMeta.
func (c *SystemMetaClient) Delete() *SystemMetaDelete {
	mutation := newSystemMetaMutation(c.config, OpDelete)
	return &SystemMetaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SystemMetaClient) DeleteOne(_m *SystemMeta) *SystemMetaDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SystemMetaClient) DeleteOneID(id int) *SystemMetaDeleteOne {
	builder := c.Delete().Where(systemmeta.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SystemMetaDeleteOne{builder}
}

// Query returns a query builder for SystemMeta.
func (c *SystemMetaClient) Query() *SystemMetaQuery {
	return &SystemMetaQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSystemMeta},
		inters: c.Interceptors(),
	}
}

// Get returns a SystemMeta entity by its id.
func (c *SystemMetaClient) Get(ctx context.Context, id int) (*SystemMeta, error) {
	return c.Query().Where(systemmeta.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SystemMetaClient) GetX(ctx context.Context, id int) *SystemMeta {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SystemMetaClient) Hooks() []Hook {
	return c.hooks.SystemMeta
}

// Interceptors returns the client interceptors.
func (c *SystemMetaClient) Interceptors() []Interceptor {
	return c.inters.SystemMeta
}

func (c *SystemMetaClient) mutate(ctx context.Context, m *SystemMetaMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SystemMetaCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SystemMetaUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SystemMetaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SystemMetaDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SystemMeta mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		FeatureClick, ImageAsset, InvoiceOrder, InvoiceProfile, InvoiceRequest, Page,
		PageView, SystemMeta []ent.Hook
	}
	inters struct {
		FeatureClick, ImageAsset, InvoiceOrder, InvoiceProfile, InvoiceRequest, Page,
		PageView, SystemMeta []ent.Interceptor
	}
)
