// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"sub2api-extension/ent/promotionclaim"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PromotionClaim is the model entity for the PromotionClaim schema.
type PromotionClaim struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PromotionID holds the value of the "promotion_id" field.
	PromotionID int `json:"promotion_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// PaymentOrderID holds the value of the "payment_order_id" field.
	PaymentOrderID int64 `json:"payment_order_id,omitempty"`
	// OutTradeNo holds the value of the "out_trade_no" field.
	OutTradeNo string `json:"out_trade_no,omitempty"`
	// OrderAmount holds the value of the "order_amount" field.
	OrderAmount float64 `json:"order_amount,omitempty"`
	// RebateAmount holds the value of the "rebate_amount" field.
	RebateAmount float64 `json:"rebate_amount,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ClaimedAt holds the value of the "claimed_at" field.
	ClaimedAt    time.Time `json:"claimed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PromotionClaim) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case promotionclaim.FieldOrderAmount, promotionclaim.FieldRebateAmount:
			values[i] = new(sql.NullFloat64)
		case promotionclaim.FieldID, promotionclaim.FieldPromotionID, promotionclaim.FieldUserID, promotionclaim.FieldPaymentOrderID:
			values[i] = new(sql.NullInt64)
		case promotionclaim.FieldOutTradeNo, promotionclaim.FieldStatus:
			values[i] = new(sql.NullString)
		case promotionclaim.FieldClaimedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PromotionClaim fields.
func (_m *PromotionClaim) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case promotionclaim.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case promotionclaim.FieldPromotionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field promotion_id", values[i])
			} else if value.Valid {
				_m.PromotionID = int(value.Int64)
			}
		case promotionclaim.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case promotionclaim.FieldPaymentOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payment_order_id", values[i])
			} else if value.Valid {
				_m.PaymentOrderID = value.Int64
			}
		case promotionclaim.FieldOutTradeNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field out_trade_no", values[i])
			} else if value.Valid {
				_m.OutTradeNo = value.String
			}
		case promotionclaim.FieldOrderAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field order_amount", values[i])
			} else if value.Valid {
				_m.OrderAmount = value.Float64
			}
		case promotionclaim.FieldRebateAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rebate_amount", values[i])
			} else if value.Valid {
				_m.RebateAmount = value.Float64
			}
		case promotionclaim.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case promotionclaim.FieldClaimedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field claimed_at", values[i])
			} else if value.Valid {
				_m.ClaimedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PromotionClaim.
// This includes values selected through modifiers, order, etc.
func (_m *PromotionClaim) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PromotionClaim.
// Note that you need to call PromotionClaim.Unwrap() before calling this method if this PromotionClaim
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PromotionClaim) Update() *PromotionClaimUpdateOne {
	return NewPromotionClaimClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PromotionClaim entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PromotionClaim) Unwrap() *PromotionClaim {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PromotionClaim is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PromotionClaim) String() string {
	var builder strings.Builder
	builder.WriteString("PromotionClaim(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("promotion_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PromotionID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("payment_order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaymentOrderID))
	builder.WriteString(", ")
	builder.WriteString("out_trade_no=")
	builder.WriteString(_m.OutTradeNo)
	builder.WriteString(", ")
	builder.WriteString("order_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderAmount))
	builder.WriteString(", ")
	builder.WriteString("rebate_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RebateAmount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("claimed_at=")
	builder.WriteString(_m.ClaimedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PromotionClaims is a parsable slice of PromotionClaim.
type PromotionClaims []*PromotionClaim
