// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sub2api-extension/ent/promotion"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PromotionCreate is the builder for creating a Promotion entity.
type PromotionCreate struct {
	config
	mutation *PromotionMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *PromotionCreate) SetTitle(v string) *PromotionCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PromotionCreate) SetDescription(v string) *PromotionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PromotionCreate) SetNillableDescription(v *string) *PromotionCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetRewardType sets the "reward_type" field.
func (_c *PromotionCreate) SetRewardType(v string) *PromotionCreate {
	_c.mutation.SetRewardType(v)
	return _c
}

// SetRewardValue sets the "reward_value" field.
func (_c *PromotionCreate) SetRewardValue(v float64) *PromotionCreate {
	_c.mutation.SetRewardValue(v)
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *PromotionCreate) SetStartsAt(v time.Time) *PromotionCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_c *PromotionCreate) SetNillableStartsAt(v *time.Time) *PromotionCreate {
	if v != nil {
		_c.SetStartsAt(*v)
	}
	return _c
}

// SetEndsAt sets the "ends_at" field.
func (_c *PromotionCreate) SetEndsAt(v time.Time) *PromotionCreate {
	_c.mutation.SetEndsAt(v)
	return _c
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_c *PromotionCreate) SetNillableEndsAt(v *time.Time) *PromotionCreate {
	if v != nil {
		_c.SetEndsAt(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *PromotionCreate) SetEnabled(v bool) *PromotionCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *PromotionCreate) SetNillableEnabled(v *bool) *PromotionCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetPublished sets the "published" field.
func (_c *PromotionCreate) SetPublished(v bool) *PromotionCreate {
	_c.mutation.SetPublished(v)
	return _c
}

// SetNillablePublished sets the "published" field if the given value is not nil.
func (_c *PromotionCreate) SetNillablePublished(v *bool) *PromotionCreate {
	if v != nil {
		_c.SetPublished(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromotionCreate) SetCreatedAt(v time.Time) *PromotionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromotionCreate) SetNillableCreatedAt(v *time.Time) *PromotionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PromotionCreate) SetUpdatedAt(v time.Time) *PromotionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PromotionCreate) SetNillableUpdatedAt(v *time.Time) *PromotionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the PromotionMutation object of the builder.
func (_c *PromotionCreate) Mutation() *PromotionMutation {
	return _c.mutation
}

// Save creates the Promotion in the database.
func (_c *PromotionCreate) Save(ctx context.Context) (*Promotion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromotionCreate) SaveX(ctx context.Context) *Promotion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromotionCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := promotion.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := promotion.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Published(); !ok {
		v := promotion.DefaultPublished
		_c.mutation.SetPublished(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := promotion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := promotion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromotionCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Promotion.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := promotion.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Promotion.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Promotion.description"`)}
	}
	if _, ok := _c.mutation.RewardType(); !ok {
		return &ValidationError{Name: "reward_type", err: errors.New(`ent: missing required field "Promotion.reward_type"`)}
	}
	if v, ok := _c.mutation.RewardType(); ok {
		if err := promotion.RewardTypeValidator(v); err != nil {
			return &ValidationError{Name: "reward_type", err: fmt.Errorf(`ent: validator failed for field "Promotion.reward_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RewardValue(); !ok {
		return &ValidationError{Name: "reward_value", err: errors.New(`ent: missing required field "Promotion.reward_value"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Promotion.enabled"`)}
	}
	if _, ok := _c.mutation.Published(); !ok {
		return &ValidationError{Name: "published", err: errors.New(`ent: missing required field "Promotion.published"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Promotion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Promotion.updated_at"`)}
	}
	return nil
}

func (_c *PromotionCreate) sqlSave(ctx context.Context) (*Promotion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromotionCreate) createSpec() (*Promotion, *sqlgraph.CreateSpec) {
	var (
		_node = &Promotion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(promotion.Table, sqlgraph.NewFieldSpec(promotion.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(promotion.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(promotion.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.RewardType(); ok {
		_spec.SetField(promotion.FieldRewardType, field.TypeString, value)
		_node.RewardType = value
	}
	if value, ok := _c.mutation.RewardValue(); ok {
		_spec.SetField(promotion.FieldRewardValue, field.TypeFloat64, value)
		_node.RewardValue = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(promotion.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = &value
	}
	if value, ok := _c.mutation.EndsAt(); ok {
		_spec.SetField(promotion.FieldEndsAt, field.TypeTime, value)
		_node.EndsAt = &value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(promotion.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Published(); ok {
		_spec.SetField(promotion.FieldPublished, field.TypeBool, value)
		_node.Published = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(promotion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(promotion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// PromotionCreateBulk is the builder for creating many Promotion entities in bulk.
type PromotionCreateBulk struct {
	config
	err      error
	builders []*PromotionCreate
}

// Save creates the Promotion entities in the database.
func (_c *PromotionCreateBulk) Save(ctx context.Context) ([]*Promotion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Promotion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromotionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromotionCreateBulk) SaveX(ctx context.Context) []*Promotion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
