// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aux-system/ent/featureclick"
	"aux-system/ent/pageview"
	"aux-system/ent/schema"
	"aux-system/ent/systemmeta"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	featureclickFields := schema.FeatureClick{}.Fields()
	_ = featureclickFields
	// featureclickDescPageID is the schema descriptor for page_id field.
	featureclickDescPageID := featureclickFields[0].Descriptor()
	// featureclick.PageIDValidator is a validator for the "page_id" field. It is called by the builders before save.
	featureclick.PageIDValidator = func() func(string) error {
		validators := featureclickDescPageID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(page_id string) error {
			for _, fn := range fns {
				if err := fn(page_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// featureclickDescFeatureID is the schema descriptor for feature_id field.
	featureclickDescFeatureID := featureclickFields[1].Descriptor()
	// featureclick.FeatureIDValidator is a validator for the "feature_id" field. It is called by the builders before save.
	featureclick.FeatureIDValidator = func() func(string) error {
		validators := featureclickDescFeatureID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(feature_id string) error {
			for _, fn := range fns {
				if err := fn(feature_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// featureclickDescVisitorID is the schema descriptor for visitor_id field.
	featureclickDescVisitorID := featureclickFields[2].Descriptor()
	// featureclick.VisitorIDValidator is a validator for the "visitor_id" field. It is called by the builders before save.
	featureclick.VisitorIDValidator = func() func(string) error {
		validators := featureclickDescVisitorID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(visitor_id string) error {
			for _, fn := range fns {
				if err := fn(visitor_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// featureclickDescIsAdmin is the schema descriptor for is_admin field.
	featureclickDescIsAdmin := featureclickFields[3].Descriptor()
	// featureclick.DefaultIsAdmin holds the default value on creation for the is_admin field.
	featureclick.DefaultIsAdmin = featureclickDescIsAdmin.Default.(bool)
	// featureclickDescCreatedAt is the schema descriptor for created_at field.
	featureclickDescCreatedAt := featureclickFields[4].Descriptor()
	// featureclick.DefaultCreatedAt holds the default value on creation for the created_at field.
	featureclick.DefaultCreatedAt = featureclickDescCreatedAt.Default.(func() time.Time)
	pageviewFields := schema.PageView{}.Fields()
	_ = pageviewFields
	// pageviewDescPageID is the schema descriptor for page_id field.
	pageviewDescPageID := pageviewFields[0].Descriptor()
	// pageview.PageIDValidator is a validator for the "page_id" field. It is called by the builders before save.
	pageview.PageIDValidator = func() func(string) error {
		validators := pageviewDescPageID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(page_id string) error {
			for _, fn := range fns {
				if err := fn(page_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// pageviewDescVisitorID is the schema descriptor for visitor_id field.
	pageviewDescVisitorID := pageviewFields[1].Descriptor()
	// pageview.VisitorIDValidator is a validator for the "visitor_id" field. It is called by the builders before save.
	pageview.VisitorIDValidator = func() func(string) error {
		validators := pageviewDescVisitorID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(visitor_id string) error {
			for _, fn := range fns {
				if err := fn(visitor_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// pageviewDescIsAdmin is the schema descriptor for is_admin field.
	pageviewDescIsAdmin := pageviewFields[2].Descriptor()
	// pageview.DefaultIsAdmin holds the default value on creation for the is_admin field.
	pageview.DefaultIsAdmin = pageviewDescIsAdmin.Default.(bool)
	// pageviewDescCreatedAt is the schema descriptor for created_at field.
	pageviewDescCreatedAt := pageviewFields[3].Descriptor()
	// pageview.DefaultCreatedAt holds the default value on creation for the created_at field.
	pageview.DefaultCreatedAt = pageviewDescCreatedAt.Default.(func() time.Time)
	systemmetaFields := schema.SystemMeta{}.Fields()
	_ = systemmetaFields
	// systemmetaDescKey is the schema descriptor for key field.
	systemmetaDescKey := systemmetaFields[0].Descriptor()
	// systemmeta.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	systemmeta.KeyValidator = systemmetaDescKey.Validators[0].(func(string) error)
}
