// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"sub2api-extension/ent/systemlog"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SystemLog is the model entity for the SystemLog schema.
type SystemLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 日志级别: DEBUG/INFO/WARN/ERROR
	Level string `json:"level,omitempty"`
	// 日志来源组件
	Source string `json:"source,omitempty"`
	// 日志消息
	Message string `json:"message,omitempty"`
	// 附加详情
	Details string `json:"details,omitempty"`
	// 请求标识
	RequestID string `json:"request_id,omitempty"`
	// 记录时间
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SystemLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case systemlog.FieldID:
			values[i] = new(sql.NullInt64)
		case systemlog.FieldLevel, systemlog.FieldSource, systemlog.FieldMessage, systemlog.FieldDetails, systemlog.FieldRequestID:
			values[i] = new(sql.NullString)
		case systemlog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SystemLog fields.
func (_m *SystemLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case systemlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case systemlog.FieldLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field level", values[i])
			} else if value.Valid {
				_m.Level = value.String
			}
		case systemlog.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case systemlog.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case systemlog.FieldDetails:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field details", values[i])
			} else if value.Valid {
				_m.Details = value.String
			}
		case systemlog.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case systemlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SystemLog.
// This includes values selected through modifiers, order, etc.
func (_m *SystemLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SystemLog.
// Note that you need to call SystemLog.Unwrap() before calling this method if this SystemLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SystemLog) Update() *SystemLogUpdateOne {
	return NewSystemLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SystemLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SystemLog) Unwrap() *SystemLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SystemLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SystemLog) String() string {
	var builder strings.Builder
	builder.WriteString("SystemLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("level=")
	builder.WriteString(_m.Level)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("details=")
	builder.WriteString(_m.Details)
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SystemLogs is a parsable slice of SystemLog.
type SystemLogs []*SystemLog
