// Code generated by ent, DO NOT EDIT.

package invoicerequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the invoicerequest type in the database.
	Label = "invoice_request"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUserEmail holds the string denoting the user_email field in the database.
	FieldUserEmail = "user_email"
	// FieldUserName holds the string denoting the user_name field in the database.
	FieldUserName = "user_name"
	// FieldInvoiceTitle holds the string denoting the invoice_title field in the database.
	FieldInvoiceTitle = "invoice_title"
	// FieldTaxpayerID holds the string denoting the taxpayer_id field in the database.
	FieldTaxpayerID = "taxpayer_id"
	// FieldContactEmail holds the string denoting the contact_email field in the database.
	FieldContactEmail = "contact_email"
	// FieldContactPhone holds the string denoting the contact_phone field in the database.
	FieldContactPhone = "contact_phone"
	// FieldRegisteredAddress holds the string denoting the registered_address field in the database.
	FieldRegisteredAddress = "registered_address"
	// FieldBankName holds the string denoting the bank_name field in the database.
	FieldBankName = "bank_name"
	// FieldBankAccount holds the string denoting the bank_account field in the database.
	FieldBankAccount = "bank_account"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAdminNote holds the string denoting the admin_note field in the database.
	FieldAdminNote = "admin_note"
	// FieldInvoiceFileName holds the string denoting the invoice_file_name field in the database.
	FieldInvoiceFileName = "invoice_file_name"
	// FieldInvoiceFilePath holds the string denoting the invoice_file_path field in the database.
	FieldInvoiceFilePath = "invoice_file_path"
	// FieldInvoiceFileMimeType holds the string denoting the invoice_file_mime_type field in the database.
	FieldInvoiceFileMimeType = "invoice_file_mime_type"
	// FieldInvoiceFileSize holds the string denoting the invoice_file_size field in the database.
	FieldInvoiceFileSize = "invoice_file_size"
	// FieldIssuedAt holds the string denoting the issued_at field in the database.
	FieldIssuedAt = "issued_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the invoicerequest in the database.
	Table = "invoice_requests"
)

// Columns holds all SQL columns for invoicerequest fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldUserEmail,
	FieldUserName,
	FieldInvoiceTitle,
	FieldTaxpayerID,
	FieldContactEmail,
	FieldContactPhone,
	FieldRegisteredAddress,
	FieldBankName,
	FieldBankAccount,
	FieldRemark,
	FieldAmount,
	FieldStatus,
	FieldAdminNote,
	FieldInvoiceFileName,
	FieldInvoiceFilePath,
	FieldInvoiceFileMimeType,
	FieldInvoiceFileSize,
	FieldIssuedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UserEmailValidator is a validator for the "user_email" field. It is called by the builders before save.
	UserEmailValidator func(string) error
	// DefaultUserName holds the default value on creation for the "user_name" field.
	DefaultUserName string
	// UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	UserNameValidator func(string) error
	// InvoiceTitleValidator is a validator for the "invoice_title" field. It is called by the builders before save.
	InvoiceTitleValidator func(string) error
	// TaxpayerIDValidator is a validator for the "taxpayer_id" field. It is called by the builders before save.
	TaxpayerIDValidator func(string) error
	// ContactEmailValidator is a validator for the "contact_email" field. It is called by the builders before save.
	ContactEmailValidator func(string) error
	// DefaultContactPhone holds the default value on creation for the "contact_phone" field.
	DefaultContactPhone string
	// ContactPhoneValidator is a validator for the "contact_phone" field. It is called by the builders before save.
	ContactPhoneValidator func(string) error
	// DefaultBankName holds the default value on creation for the "bank_name" field.
	DefaultBankName string
	// BankNameValidator is a validator for the "bank_name" field. It is called by the builders before save.
	BankNameValidator func(string) error
	// DefaultBankAccount holds the default value on creation for the "bank_account" field.
	DefaultBankAccount string
	// BankAccountValidator is a validator for the "bank_account" field. It is called by the builders before save.
	BankAccountValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultInvoiceFileName holds the default value on creation for the "invoice_file_name" field.
	DefaultInvoiceFileName string
	// InvoiceFileNameValidator is a validator for the "invoice_file_name" field. It is called by the builders before save.
	InvoiceFileNameValidator func(string) error
	// DefaultInvoiceFilePath holds the default value on creation for the "invoice_file_path" field.
	DefaultInvoiceFilePath string
	// InvoiceFilePathValidator is a validator for the "invoice_file_path" field. It is called by the builders before save.
	InvoiceFilePathValidator func(string) error
	// DefaultInvoiceFileMimeType holds the default value on creation for the "invoice_file_mime_type" field.
	DefaultInvoiceFileMimeType string
	// InvoiceFileMimeTypeValidator is a validator for the "invoice_file_mime_type" field. It is called by the builders before save.
	InvoiceFileMimeTypeValidator func(string) error
	// DefaultInvoiceFileSize holds the default value on creation for the "invoice_file_size" field.
	DefaultInvoiceFileSize int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the InvoiceRequest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserEmail orders the results by the user_email field.
func ByUserEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserEmail, opts...).ToFunc()
}

// ByUserName orders the results by the user_name field.
func ByUserName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserName, opts...).ToFunc()
}

// ByInvoiceTitle orders the results by the invoice_title field.
func ByInvoiceTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceTitle, opts...).ToFunc()
}

// ByTaxpayerID orders the results by the taxpayer_id field.
func ByTaxpayerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxpayerID, opts...).ToFunc()
}

// ByContactEmail orders the results by the contact_email field.
func ByContactEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactEmail, opts...).ToFunc()
}

// ByContactPhone orders the results by the contact_phone field.
func ByContactPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactPhone, opts...).ToFunc()
}

// ByRegisteredAddress orders the results by the registered_address field.
func ByRegisteredAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegisteredAddress, opts...).ToFunc()
}

// ByBankName orders the results by the bank_name field.
func ByBankName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBankName, opts...).ToFunc()
}

// ByBankAccount orders the results by the bank_account field.
func ByBankAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBankAccount, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAdminNote orders the results by the admin_note field.
func ByAdminNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminNote, opts...).ToFunc()
}

// ByInvoiceFileName orders the results by the invoice_file_name field.
func ByInvoiceFileName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceFileName, opts...).ToFunc()
}

// ByInvoiceFilePath orders the results by the invoice_file_path field.
func ByInvoiceFilePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceFilePath, opts...).ToFunc()
}

// ByInvoiceFileMimeType orders the results by the invoice_file_mime_type field.
func ByInvoiceFileMimeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceFileMimeType, opts...).ToFunc()
}

// ByInvoiceFileSize orders the results by the invoice_file_size field.
func ByInvoiceFileSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceFileSize, opts...).ToFunc()
}

// ByIssuedAt orders the results by the issued_at field.
func ByIssuedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
