// Code generated by ent, DO NOT EDIT.

package notificationdelivery

import (
	"sub2api-extension/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLTE(FieldID, id))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldChannelID, v))
}

// ChannelName applies equality check predicate on the "channel_name" field. It's identical to ChannelNameEQ.
func ChannelName(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldChannelName, v))
}

// ChannelType applies equality check predicate on the "channel_type" field. It's identical to ChannelTypeEQ.
func ChannelType(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldChannelType, v))
}

// Event applies equality check predicate on the "event" field. It's identical to EventEQ.
func Event(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldEvent, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldStatus, v))
}

// Recipient applies equality check predicate on the "recipient" field. It's identical to RecipientEQ.
func Recipient(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldRecipient, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldSubject, v))
}

// Payload applies equality check predicate on the "payload" field. It's identical to PayloadEQ.
func Payload(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldPayload, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldErrorMessage, v))
}

// Attempts applies equality check predicate on the "attempts" field. It's identical to AttemptsEQ.
func Attempts(v int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldAttempts, v))
}

// SentAt applies equality check predicate on the "sent_at" field. It's identical to SentAtEQ.
func SentAt(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldSentAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldCreatedAt, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDGT applies the GT predicate on the "channel_id" field.
func ChannelIDGT(v int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGT(FieldChannelID, v))
}

// ChannelIDGTE applies the GTE predicate on the "channel_id" field.
func ChannelIDGTE(v int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGTE(FieldChannelID, v))
}

// ChannelIDLT applies the LT predicate on the "channel_id" field.
func ChannelIDLT(v int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLT(FieldChannelID, v))
}

// ChannelIDLTE applies the LTE predicate on the "channel_id" field.
func ChannelIDLTE(v int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLTE(FieldChannelID, v))
}

// ChannelIDIsNil applies the IsNil predicate on the "channel_id" field.
func ChannelIDIsNil() predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIsNull(FieldChannelID))
}

// ChannelIDNotNil applies the NotNil predicate on the "channel_id" field.
func ChannelIDNotNil() predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotNull(FieldChannelID))
}

// ChannelNameEQ applies the EQ predicate on the "channel_name" field.
func ChannelNameEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldChannelName, v))
}

// ChannelNameNEQ applies the NEQ predicate on the "channel_name" field.
func ChannelNameNEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNEQ(FieldChannelName, v))
}

// ChannelNameIn applies the In predicate on the "channel_name" field.
func ChannelNameIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIn(FieldChannelName, vs...))
}

// ChannelNameNotIn applies the NotIn predicate on the "channel_name" field.
func ChannelNameNotIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotIn(FieldChannelName, vs...))
}

// ChannelNameGT applies the GT predicate on the "channel_name" field.
func ChannelNameGT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGT(FieldChannelName, v))
}

// ChannelNameGTE applies the GTE predicate on the "channel_name" field.
func ChannelNameGTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGTE(FieldChannelName, v))
}

// ChannelNameLT applies the LT predicate on the "channel_name" field.
func ChannelNameLT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLT(FieldChannelName, v))
}

// ChannelNameLTE applies the LTE predicate on the "channel_name" field.
func ChannelNameLTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLTE(FieldChannelName, v))
}

// ChannelNameContains applies the Contains predicate on the "channel_name" field.
func ChannelNameContains(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContains(FieldChannelName, v))
}

// ChannelNameHasPrefix applies the HasPrefix predicate on the "channel_name" field.
func ChannelNameHasPrefix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasPrefix(FieldChannelName, v))
}

// ChannelNameHasSuffix applies the HasSuffix predicate on the "channel_name" field.
func ChannelNameHasSuffix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasSuffix(FieldChannelName, v))
}

// ChannelNameEqualFold applies the EqualFold predicate on the "channel_name" field.
func ChannelNameEqualFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEqualFold(FieldChannelName, v))
}

// ChannelNameContainsFold applies the ContainsFold predicate on the "channel_name" field.
func ChannelNameContainsFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContainsFold(FieldChannelName, v))
}

// ChannelTypeEQ applies the EQ predicate on the "channel_type" field.
func ChannelTypeEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldChannelType, v))
}

// ChannelTypeNEQ applies the NEQ predicate on the "channel_type" field.
func ChannelTypeNEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNEQ(FieldChannelType, v))
}

// ChannelTypeIn applies the In predicate on the "channel_type" field.
func ChannelTypeIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIn(FieldChannelType, vs...))
}

// ChannelTypeNotIn applies the NotIn predicate on the "channel_type" field.
func ChannelTypeNotIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotIn(FieldChannelType, vs...))
}

// ChannelTypeGT applies the GT predicate on the "channel_type" field.
func ChannelTypeGT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGT(FieldChannelType, v))
}

// ChannelTypeGTE applies the GTE predicate on the "channel_type" field.
func ChannelTypeGTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGTE(FieldChannelType, v))
}

// ChannelTypeLT applies the LT predicate on the "channel_type" field.
func ChannelTypeLT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLT(FieldChannelType, v))
}

// ChannelTypeLTE applies the LTE predicate on the "channel_type" field.
func ChannelTypeLTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLTE(FieldChannelType, v))
}

// ChannelTypeContains applies the Contains predicate on the "channel_type" field.
func ChannelTypeContains(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContains(FieldChannelType, v))
}

// ChannelTypeHasPrefix applies the HasPrefix predicate on the "channel_type" field.
func ChannelTypeHasPrefix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasPrefix(FieldChannelType, v))
}

// ChannelTypeHasSuffix applies the HasSuffix predicate on the "channel_type" field.
func ChannelTypeHasSuffix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasSuffix(FieldChannelType, v))
}

// ChannelTypeEqualFold applies the EqualFold predicate on the "channel_type" field.
func ChannelTypeEqualFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEqualFold(FieldChannelType, v))
}

// ChannelTypeContainsFold applies the ContainsFold predicate on the "channel_type" field.
func ChannelTypeContainsFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContainsFold(FieldChannelType, v))
}

// EventEQ applies the EQ predicate on the "event" field.
func EventEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldEvent, v))
}

// EventNEQ applies the NEQ predicate on the "event" field.
func EventNEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNEQ(FieldEvent, v))
}

// EventIn applies the In predicate on the "event" field.
func EventIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIn(FieldEvent, vs...))
}

// EventNotIn applies the NotIn predicate on the "event" field.
func EventNotIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotIn(FieldEvent, vs...))
}

// EventGT applies the GT predicate on the "event" field.
func EventGT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGT(FieldEvent, v))
}

// EventGTE applies the GTE predicate on the "event" field.
func EventGTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGTE(FieldEvent, v))
}

// EventLT applies the LT predicate on the "event" field.
func EventLT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLT(FieldEvent, v))
}

// EventLTE applies the LTE predicate on the "event" field.
func EventLTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLTE(FieldEvent, v))
}

// EventContains applies the Contains predicate on the "event" field.
func EventContains(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContains(FieldEvent, v))
}

// EventHasPrefix applies the HasPrefix predicate on the "event" field.
func EventHasPrefix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasPrefix(FieldEvent, v))
}

// EventHasSuffix applies the HasSuffix predicate on the "event" field.
func EventHasSuffix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasSuffix(FieldEvent, v))
}

// EventEqualFold applies the EqualFold predicate on the "event" field.
func EventEqualFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEqualFold(FieldEvent, v))
}

// EventContainsFold applies the ContainsFold predicate on the "event" field.
func EventContainsFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContainsFold(FieldEvent, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContainsFold(FieldStatus, v))
}

// RecipientEQ applies the EQ predicate on the "recipient" field.
func RecipientEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldRecipient, v))
}

// RecipientNEQ applies the NEQ predicate on the "recipient" field.
func RecipientNEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNEQ(FieldRecipient, v))
}

// RecipientIn applies the In predicate on the "recipient" field.
func RecipientIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIn(FieldRecipient, vs...))
}

// RecipientNotIn applies the NotIn predicate on the "recipient" field.
func RecipientNotIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotIn(FieldRecipient, vs...))
}

// RecipientGT applies the GT predicate on the "recipient" field.
func RecipientGT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGT(FieldRecipient, v))
}

// RecipientGTE applies the GTE predicate on the "recipient" field.
func RecipientGTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGTE(FieldRecipient, v))
}

// RecipientLT applies the LT predicate on the "recipient" field.
func RecipientLT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLT(FieldRecipient, v))
}

// RecipientLTE applies the LTE predicate on the "recipient" field.
func RecipientLTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLTE(FieldRecipient, v))
}

// RecipientContains applies the Contains predicate on the "recipient" field.
func RecipientContains(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContains(FieldRecipient, v))
}

// RecipientHasPrefix applies the HasPrefix predicate on the "recipient" field.
func RecipientHasPrefix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasPrefix(FieldRecipient, v))
}

// RecipientHasSuffix applies the HasSuffix predicate on the "recipient" field.
func RecipientHasSuffix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasSuffix(FieldRecipient, v))
}

// RecipientEqualFold applies the EqualFold predicate on the "recipient" field.
func RecipientEqualFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEqualFold(FieldRecipient, v))
}

// RecipientContainsFold applies the ContainsFold predicate on the "recipient" field.
func RecipientContainsFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContainsFold(FieldRecipient, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContainsFold(FieldSubject, v))
}

// PayloadEQ applies the EQ predicate on the "payload" field.
func PayloadEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldPayload, v))
}

// PayloadNEQ applies the NEQ predicate on the "payload" field.
func PayloadNEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNEQ(FieldPayload, v))
}

// PayloadIn applies the In predicate on the "payload" field.
func PayloadIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIn(FieldPayload, vs...))
}

// PayloadNotIn applies the NotIn predicate on the "payload" field.
func PayloadNotIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotIn(FieldPayload, vs...))
}

// PayloadGT applies the GT predicate on the "payload" field.
func PayloadGT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGT(FieldPayload, v))
}

// PayloadGTE applies the GTE predicate on the "payload" field.
func PayloadGTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGTE(FieldPayload, v))
}

// PayloadLT applies the LT predicate on the "payload" field.
func PayloadLT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLT(FieldPayload, v))
}

// PayloadLTE applies the LTE predicate on the "payload" field.
func PayloadLTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLTE(FieldPayload, v))
}

// PayloadContains applies the Contains predicate on the "payload" field.
func PayloadContains(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContains(FieldPayload, v))
}

// PayloadHasPrefix applies the HasPrefix predicate on the "payload" field.
func PayloadHasPrefix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasPrefix(FieldPayload, v))
}

// PayloadHasSuffix applies the HasSuffix predicate on the "payload" field.
func PayloadHasSuffix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasSuffix(FieldPayload, v))
}

// PayloadIsNil applies the IsNil predicate on the "payload" field.
func PayloadIsNil() predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIsNull(FieldPayload))
}

// PayloadNotNil applies the NotNil predicate on the "payload" field.
func PayloadNotNil() predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotNull(FieldPayload))
}

// PayloadEqualFold applies the EqualFold predicate on the "payload" field.
func PayloadEqualFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEqualFold(FieldPayload, v))
}

// PayloadContainsFold applies the ContainsFold predicate on the "payload" field.
func PayloadContainsFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContainsFold(FieldPayload, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldContainsFold(FieldErrorMessage, v))
}

// AttemptsEQ applies the EQ predicate on the "attempts" field.
func AttemptsEQ(v int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldAttempts, v))
}

// AttemptsNEQ applies the NEQ predicate on the "attempts" field.
func AttemptsNEQ(v int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNEQ(FieldAttempts, v))
}

// AttemptsIn applies the In predicate on the "attempts" field.
func AttemptsIn(vs ...int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIn(FieldAttempts, vs...))
}

// AttemptsNotIn applies the NotIn predicate on the "attempts" field.
func AttemptsNotIn(vs ...int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotIn(FieldAttempts, vs...))
}

// AttemptsGT applies the GT predicate on the "attempts" field.
func AttemptsGT(v int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGT(FieldAttempts, v))
}

// AttemptsGTE applies the GTE predicate on the "attempts" field.
func AttemptsGTE(v int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGTE(FieldAttempts, v))
}

// AttemptsLT applies the LT predicate on the "attempts" field.
func AttemptsLT(v int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLT(FieldAttempts, v))
}

// AttemptsLTE applies the LTE predicate on the "attempts" field.
func AttemptsLTE(v int) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLTE(FieldAttempts, v))
}

// SentAtEQ applies the EQ predicate on the "sent_at" field.
func SentAtEQ(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldSentAt, v))
}

// SentAtNEQ applies the NEQ predicate on the "sent_at" field.
func SentAtNEQ(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNEQ(FieldSentAt, v))
}

// SentAtIn applies the In predicate on the "sent_at" field.
func SentAtIn(vs ...time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIn(FieldSentAt, vs...))
}

// SentAtNotIn applies the NotIn predicate on the "sent_at" field.
func SentAtNotIn(vs ...time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotIn(FieldSentAt, vs...))
}

// SentAtGT applies the GT predicate on the "sent_at" field.
func SentAtGT(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGT(FieldSentAt, v))
}

// SentAtGTE applies the GTE predicate on the "sent_at" field.
func SentAtGTE(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGTE(FieldSentAt, v))
}

// SentAtLT applies the LT predicate on the "sent_at" field.
func SentAtLT(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLT(FieldSentAt, v))
}

// SentAtLTE applies the LTE predicate on the "sent_at" field.
func SentAtLTE(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLTE(FieldSentAt, v))
}

// SentAtIsNil applies the IsNil predicate on the "sent_at" field.
func SentAtIsNil() predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIsNull(FieldSentAt))
}

// SentAtNotNil applies the NotNil predicate on the "sent_at" field.
func SentAtNotNil() predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotNull(FieldSentAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NotificationDelivery) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NotificationDelivery) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NotificationDelivery) predicate.NotificationDelivery {
	return predicate.NotificationDelivery(sql.NotPredicates(p))
}
