// @ts-nocheck
function H(s){const t=[];
if(s<=0)return t;
const e=Math.PI*(3-Math.sqrt(5));
for(let n=0;
n<s;
n++){const i=s===1?0:1-n/(s-1)*2,a=Math.sqrt(Math.max(0,1-i*i)),r=e*n;
t.push([Math.cos(r)*a,i,Math.sin(r)*a])}return t}function W(s,t,e){const[n,i,a]=s,r=Math.cos(e),l=Math.sin(e),h=n*r+a*l,o=-n*l+a*r,c=Math.cos(t),u=Math.sin(t),f=i*c-o*u,m=i*u+o*c;
return[h,f,m]}const tt=.6,G=-.45,P=.2,R=.85,N=.34;
let x=G,nt=0,X=1;
function et(s,t,e){const n=(s+1)/2,i=Math.pow(n,2*(e??1));
return{a:.06+.94*i,r:t*(.28+.72*i)}}const J=document.createElement("canvas").getContext("2d");
function lt(s){J.fillStyle="#000",J.fillStyle=s;
const t=J.fillStyle;
if(t[0]==="#"){let n=t.slice(1);
n.length===3&&(n=n.split("").map(a=>a+a).join(""));
const i=parseInt(n,16);
return[i>>16&255,i>>8&255,i&255].join(",")}const e=t.match(/(\d+),\s*(\d+),\s*(\d+)/);
return e?`${e[1]},${e[2]},${e[3]}`:"17,17,20"}function ct(s){return Math.round(Math.min(420,Math.max(14,s*1.6)))}function E(s,t){var e=Math.max(.8,s/42);
return(t==="logo"||t==="svg")&&(e*=.5),e}const V=s=>Math.max(-1,Math.min(1,s));
function st(s){return H(s).map(([t,e,n])=>({x:t,y:e,z:n,u:(Math.atan2(n,t)+Math.PI)/(2*Math.PI),v:(Math.asin(V(e))+Math.PI/2)/Math.PI}))}function at(s,t,e,n,i,a){var r=[];
if(s.length===0){for(var l=0;
l<n;
l++){var h=l/n*2*Math.PI,o=Math.sqrt((l+.5)/n),c=Math.cos(h)*o,u=Math.sin(h)*o;
r.push({x:c,y:u,z:0,u:(c+1)/2,v:(u+1)/2})}return r}for(var f=new Uint8Array(t*e),m=t,d=e,M=0,w=0,g=0;
g<s.length;
g++){var v=s[g];
f[v[1]*t+v[0]]=1,v[0]<m&&(m=v[0]),v[0]>M&&(M=v[0]),v[1]<d&&(d=v[1]),v[1]>w&&(w=v[1])}function y($,j){return $>=0&&$<t&&j>=0&&j<e&&f[j*t+$]===1}var b=Math.min(t,e);
function p($,j,ht){var Q=($-t/2)/(b/2),Z=(j-e/2)/(b/2);
return{x:Q,y:-Z,z:ht,u:(Q+1)/2,v:(-Z+1)/2}}for(var L=M-m+1,q=w-d+1,U=s.length/(L*q),_=Math.max(6,Math.min(120,Math.round(Math.sqrt(n/Math.max(.02,U))))),k=Math.max(L,q)/_,I=Math.max(2,Math.floor(a)),T=0;
T<=_;
T++){var S=m+(T+.5)*k;
if(S>M)break;
for(var C=0;
C<=_;
C++){var F=d+(C+.5)*k;
if(F>w)break;
var D=Math.round(S),z=Math.round(F);
if(y(D,z))for(var B=0;
B<I;
B++){var ot=I===1?0:-i+2*i*B/(I-1);
r.push(p(D,z,ot))}}}return r}const it=new Map;
function ut(s,t){it.set(s,t)}function dt(s){return it.get(s)}function ft(s,t,e,n,i){return new Promise(function(a,r){var l=URL.createObjectURL(s),h=new Image;
h.onload=function(){try{var o=256,c=256,u=document.createElement("canvas");
u.width=o,u.height=c;
var f=u.getContext("2d");
f.clearRect(0,0,o,c);
var m=h.width||o,d=h.height||c,M=Math.min(o/m,c/d)*.92,w=m*M,g=d*M;
f.drawImage(h,(o-w)/2,(c-g)/2,w,g);
for(var v=f.getImageData(0,0,o,c).data,y=[],b=0;
b<c;
b++)for(var p=0;
p<o;
p++)v[(b*o+p)*4+3]>128&&y.push([p,b]);
ut(t,at(y,o,c,e,i??N,n)),a()}catch(L){r(L)}finally{URL.revokeObjectURL(l)}},h.onerror=function(){URL.revokeObjectURL(l),r(new Error("SVG failed to load"))},h.src=l})}const K=new Map;
function Mt(s,t,e,n){const i=t+"|"+s+"|"+e+"|"+(n??N);
if(K.has(i))return K.get(i);
const a=mt(t||"AI",s,e,n);
return K.set(i,a),a}function mt(s,t,e,n){var i=256,a=256,r=document.createElement("canvas");
r.width=i,r.height=a;
var l=r.getContext("2d");
l.clearRect(0,0,i,a),l.fillStyle="#fff",l.textAlign="center",l.textBaseline="middle";
var h='bold {S}px "Arial", "Helvetica", "PingFang SC", sans-serif',o=220;
for(l.font=h.replace("{S}",String(o));
o>12&&l.measureText(s).width>i*.84;
)o-=4,l.font=h.replace("{S}",String(o));
o=Math.min(o,Math.floor(a*.82)),l.font=h.replace("{S}",String(o)),l.fillText(s,i/2,a/2+o*.02);
for(var c=l.getImageData(0,0,i,a).data,u=[],f=0;
f<a;
f++)for(var m=0;
m<i;
m++)c[(f*i+m)*4+3]>128&&u.push([m,f]);
return at(u,i,a,t,n??N,e)}function A(s,t,e,n){const i=t*.42,a=t/2,r=t/2,l=n.tilt!=null?n.tilt:x,h=n.phase!=null?n.phase:nt,o=n.scramble!=null?n.scramble:0,c=n.alpha!=null?n.alpha:1,u=n.scale!=null?n.scale:1,f=n.contrast!=null?n.contrast:1,m=n.displace,d=n.modulate,M=n.twist!=null?n.twist:0,w=M*(1+.3*Math.sin(e*.8)),g=n.points;
for(let v=0;
v<g.length;
v++){const y=g[v];
let b=y.x,p=y.z;
if(M!==0){const C=w*y.y,F=Math.cos(C),D=Math.sin(C),z=b*F+p*D,B=-b*D+p*F;
b=z,p=B}const L=W([b,y.y,p],l,e*n.spin+h),q=m?m(y):1,U=i*u*q;
let _=a+L[0]*U,k=r-L[1]*U;
o>0&&(_+=Math.sin(v*12.9898+e*1.5)*o,k+=Math.cos(v*78.233+e*1.7)*o);
const I=et(L[2],n.dotR*(n.dotScale!=null?n.dotScale:X),f);
let T=I.a*c,S=I.r;
if(d){const C=d(y,v,[y.u,y.v]);
T*=.3+.7*C,S*=.55+.7*C}s.dots.push({x:_,y:k,r:S,a:T})}}function vt(s,t){const e=Math.atan2(s.z,s.x);
let n=t*1.2-(e+P*t);
n=Math.atan2(Math.sin(n),Math.cos(n));
const i=.42;
return Math.exp(-(n*n)/(2*i*i))}function gt(s,t){const e=Math.asin(V(s.y)),n=Math.atan2(s.z,s.x);
return .5+.5*Math.sin(e*5-t*3.2+n*2.5)}function wt(s,t){const e=V(s.z),n=Math.acos(e),i=t*.5%2,a=i<1?i*Math.PI:(2-i)*Math.PI,r=.45,l=Math.abs(n-a);
return Math.exp(-(l*l)/(2*r*r))}function yt(s,t){const e=Math.asin(V(s.y)),n=Math.sin(t*.9)*(Math.PI/2-.2),i=e-n;
return .25+.95*Math.exp(-(i*i)/(2*.5*.5))}function xt(s,t){const e=Math.atan2(s.z,s.x);
let n=e-t*1;
n=Math.atan2(Math.sin(n),Math.cos(n));
const i=Math.exp(-(n*n)/2);
let a=e-t*1-Math.PI;
a=Math.atan2(Math.sin(a),Math.cos(a));
const r=Math.exp(-(a*a)/2);
return Math.max(i,r)}function bt(s,t){const e=Math.atan2(s.z,s.x),n=Math.asin(V(s.y));
let i=e-2.4*n-t*.8;
i=Math.atan2(Math.sin(i),Math.cos(i));
const a=Math.min(Math.abs(i),Math.abs(i-Math.PI));
return Math.exp(-(a*a)/(2*.3*.3))}function St(s,t,e,n){const r=Math.atan2(e-.5,t-.5),l=Math.hypot(t-.5,e-.5);
switch(s){case"sweep":{let h=t-n*1.2%1;
h=h-Math.round(h);
const o=.16;
return Math.exp(-(h*h)/(2*o*o))}case"listening":return .5+.5*Math.sin((t-.5)*6-n*3.2+(e-.5)*4);
case"pulse":{const h=n*.5%2,o=h<1?h*.7:(2-h)*.7,c=.18,u=Math.abs(l-o);
return Math.exp(-(u*u)/(2*c*c))}case"tide":{const h=(t+e)/2,o=.5+.5*Math.sin(n*.9),c=h-o;
return .25+.95*Math.exp(-(c*c)/(2*.18*.18))}case"aurora":{let o=r-n*1;
o=Math.atan2(Math.sin(o),Math.cos(o));
const c=Math.exp(-(o*o)/(2*.6*.6));
let u=r-n*1-Math.PI*2/3;
u=Math.atan2(Math.sin(u),Math.cos(u));
const f=Math.exp(-(u*u)/(2*.6*.6));
return Math.max(c,f)}case"spiral":{let h=r-6*l-n*.8;
h=Math.atan2(Math.sin(h),Math.cos(h));
const o=Math.min(Math.abs(h),Math.abs(h-Math.PI));
return Math.exp(-(o*o)/(2*.3*.3))}default:return 1}}function O(s,t,e){if(t==="logo"||t==="svg")return(n,i,a)=>St(s,a[0],a[1],e);
switch(s){case"sweep":return n=>vt(n,e);
case"listening":return n=>gt(n,e);
case"pulse":return n=>wt(n,e);
case"tide":return n=>yt(n,e);
case"aurora":return n=>xt(n,e);
case"spiral":return n=>bt(n,e);
default:return()=>1}}function pt(s,t,e,n,i){const a={dots:[],lines:[]},r=E(s,n);
if(n==="sphere"){A(a,s,t,{points:i,dotR:r,spin:P,tilt:x,alpha:R,contrast:e});
const l=s*.42,h=s/2,o=s/2;
for(let c=0;
c<3;
c++){const u=l*(1.12+c*.08),f=x+c*.4,m=t*1.4*(1+c*.25)+c*2.1;
for(let d=0;
d<6;
d++){const M=m-d*.12,w=Math.cos(M)*u,g=Math.sin(M)*u*Math.sin(f);
a.dots.push({x:h+w,y:o+g,r:r*X*(1.4-d*.15),a:.9-d*.13})}}return a}return A(a,s,t,{points:i,dotR:r,spin:P,tilt:x,alpha:R,contrast:e}),a}function Pt(s,t,e,n,i){const a={dots:[],lines:[]},r=E(s,n);
return A(a,s,t,{points:i,dotR:r,spin:P,tilt:x,alpha:R,contrast:e,modulate:O("sweep",n,t)}),a}function kt(s,t,e,n,i){const a={dots:[],lines:[]},r=E(s,n),l=t*.08%1,o=(Math.sin(l*Math.PI*2)*.5+.5)*s*.05;
return A(a,s,t,{points:i,dotR:r,spin:P,tilt:x,scramble:o,alpha:R,contrast:e}),a}function Rt(s,t,e,n,i){const a={dots:[],lines:[]},r=E(s,n);
return A(a,s,t,{points:i,dotR:r,spin:P,tilt:x,alpha:R,contrast:e,modulate:O("listening",n,t)}),a}function At(s,t,e,n,i){const a={dots:[],lines:[]},r=E(s,n),l=s*.42,h=s/2,o=s/2;
if(n!=="sphere")return A(a,s,t,{points:i,dotR:r,spin:P,tilt:x,alpha:R,contrast:e}),a;
A(a,s,t,{points:i,dotR:r,spin:P,tilt:x,alpha:R,contrast:e});
const c=H(11),u=c.length,f=[];
for(let d=0;
d<u;
d++){const M=W(c[d],x,t*P);
f.push(M);
const w=et(M[2],r*X*2,e),g=.5+.5*Math.sin(t*2.2+d);
a.dots.push({x:h+M[0]*l,y:o-M[1]*l,r:w.r,a:Math.min(1,w.a*(.55+.45*g))})}const m=t*.32%1;
for(let d=0;
d<u;
d++)for(let M=d+1;
M<u;
M++){const w=f[d],g=f[M],v=h+w[0]*l,y=o-w[1]*l,b=h+g[0]*l,p=o-g[1]*l;
if(Math.hypot(v-b,y-p)<l*1.05){const q=(d*31+M*17)%100/100,U=Math.max(0,(1-(m-q)/.3)*.175),_=Math.min(.375,.2+U);
a.lines.push({x1:v,y1:y,x2:b,y2:p,a:_,w:r*.75})}}return a}function It(s,t,e,n,i){const a={dots:[],lines:[]};
return A(a,s,t,{points:i,dotR:E(s,n),spin:P,tilt:x,alpha:R,contrast:e}),a}function Tt(s,t,e,n,i){const a={dots:[],lines:[]},r=E(s,n),l=1+.08*Math.sin(t*1.5);
return A(a,s,t,{points:i,dotR:r,spin:P,tilt:x,alpha:R+.18*Math.sin(t*1.5),scale:l,contrast:e}),a}function Et(s,t,e,n,i){const a={dots:[],lines:[]},r=E(s,n);
return A(a,s,t,{points:i,dotR:r,spin:P,tilt:x,alpha:R,contrast:e,modulate:(l,h)=>{const o=h*1.7%(Math.PI*2),c=Math.max(0,Math.sin(t*2.4+o));
return c*c}}),a}function Lt(s,t,e,n,i){const a={dots:[],lines:[]},r=E(s,n);
return A(a,s,t,{points:i,dotR:r,spin:P,tilt:x,alpha:R,contrast:e,modulate:O("pulse",n,t)}),a}function _t(s,t,e,n,i){const a={dots:[],lines:[]},r=E(s,n);
return A(a,s,t,{points:i,dotR:r,spin:P,tilt:x,alpha:R,contrast:e,modulate:O("tide",n,t)}),a}function qt(s,t,e,n,i){const a={dots:[],lines:[]},r=E(s,n);
return A(a,s,t,{points:i,dotR:r,spin:P,tilt:x,alpha:R,contrast:e,modulate:O("aurora",n,t)}),a}function Ct(s,t,e,n,i){const a={dots:[],lines:[]},r=E(s,n);
return A(a,s,t,{points:i,dotR:r,spin:P,tilt:x,alpha:R,contrast:e,modulate:O("spiral",n,t)}),a}const Ut={working:pt,sweep:Pt,shake:kt,listening:Rt,network:At,spin:It,breathing:Tt,twinkle:Et,pulse:Lt,tide:_t,aurora:qt,spiral:Ct};
function Ot(s,t,e,n,i,a,r,l,h,o,c,u,f,m,d){x=f??G,nt=m??0,X=u??1;
const M=e*i,w=r??tt,g=l||"sphere",v=o??1,y=c??5,b=d??N,p=g==="logo"||g==="svg",L=ct(t),q=Math.round(L*(p?1.8:1)*v),U=g==="logo"?Mt(q,h||"AI",y,b):g==="svg"&&dt(h)||st(q),_=Ut[n](t,M,w,g,U);
s.clearRect(0,0,t,t);
const k=.85,I=t/2,T=t/2;
for(const S of _.lines)s.strokeStyle=`rgba(${a},${S.a})`,s.lineWidth=S.w*k,s.beginPath(),s.moveTo(I+(S.x1-I)*k,T+(S.y1-T)*k),s.lineTo(I+(S.x2-I)*k,T+(S.y2-T)*k),s.stroke();
for(const S of _.dots)s.fillStyle=`rgba(${a},${S.a})`,s.beginPath(),s.arc(I+(S.x-I)*k,T+(S.y-T)*k,S.r*k,0,Math.PI*2),s.fill()}const Y=[];
let rt=!1;
function Ft(){if(rt)return;
rt=!0;
const s=t=>{const e=t/1e3;
for(const n of Y)n.draw(e);
requestAnimationFrame(s)};
requestAnimationFrame(s)}class Dt{constructor(t,e={}){this.canvas=t,this.ctx=t.getContext("2d"),this.state=e.state||"working",this.size=e.size!=null?e.size:64,this.speed=e.speed!=null?e.speed:3,this.theme=e.theme||"auto",this.color=e.color||null,this.contrast=e.contrast!=null?e.contrast:tt,this.shape=e.shape||"sphere",this.text=e.text||"AI",this.density=e.density!=null?e.density:1,this.layers=e.layers!=null?e.layers:5,this.dotScale=e.dotScale!=null?e.dotScale:1,this.tilt=e.tilt!=null?e.tilt:G,this.rotation=e.rotation!=null?e.rotation:0,this.depth=e.depth!=null?e.depth:N,this.paused=!!e.paused,this.props={state:this.state,size:this.size,speed:this.speed,theme:this.theme,color:this.color,contrast:this.contrast,shape:this.shape,text:this.text,density:this.density,layers:this.layers,dotScale:this.dotScale,tilt:this.tilt,rotation:this.rotation,depth:this.depth,paused:this.paused},this.dpr=Math.min(window.devicePixelRatio||1,2),this.visible=document.visibilityState==="visible",this.onScreen=!0,this.reduce=window.matchMedia("(prefers-reduced-motion: reduce)").matches,this.frozen=0,this.dirty=!0,this.lastSize=-1,t.setAttribute("role","img"),t.setAttribute("aria-label",e["aria-label"]||this.state+" orb"),t.style.display="block",this.io=new IntersectionObserver(([n])=>{this.onScreen=n.isIntersecting},{threshold:0}),this.io.observe(t),this.onVis=()=>{this.visible=document.visibilityState==="visible"},document.addEventListener("visibilitychange",this.onVis),this.mo=new MutationObserver(()=>{this.dirty=!0}),this.mo.observe(document.documentElement,{attributes:!0,attributeFilter:["data-theme"]}),this.mq=window.matchMedia("(prefers-color-scheme: dark)"),this.onMq=()=>{this.dirty=!0},this.mq.addEventListener("change",this.onMq),Y.push(this),Ft()}update(t){Object.assign(this.props,t),t.state!=null&&(this.state=t.state),t.size!=null&&(this.size=t.size),t.speed!=null&&(this.speed=t.speed),t.theme!=null&&(this.theme=t.theme),t.color!==void 0&&(this.color=t.color),t.contrast!==void 0&&(this.contrast=t.contrast),t.shape!=null&&(this.shape=t.shape),t.text!==void 0&&(this.text=t.text),t.density!==void 0&&(this.density=t.density),t.layers!==void 0&&(this.layers=t.layers),t.dotScale!==void 0&&(this.dotScale=t.dotScale),t.tilt!==void 0&&(this.tilt=t.tilt),t.rotation!==void 0&&(this.rotation=t.rotation),t.depth!==void 0&&(this.depth=t.depth),t.paused!=null&&(this.paused=t.paused),this.dirty=!0}resolveDark(){const t=this.props.theme;
if(t==="dark")return!0;
if(t==="light")return!1;
const e=document.documentElement.getAttribute("data-theme");
return e==="dark"?!0:e==="light"?!1:window.matchMedia("(prefers-color-scheme: dark)").matches}resize(){const t=this.props.size;
t!==this.lastSize&&(this.lastSize=t,this.canvas.width=Math.round(t*this.dpr),this.canvas.height=Math.round(t*this.dpr),this.canvas.style.width=t+"px",this.canvas.style.height=t+"px")}draw(t){this.visible&&this.onScreen&&!this.props.paused&&!this.reduce?(this.frozen=t,this._render(),this.dirty=!1):this.reduce?(this._render(),this.dirty=!1):this.dirty&&(this._render(),this.dirty=!1)}_render(){this.resize(),this.ctx.setTransform(this.dpr,0,0,this.dpr,0,0);
const t=this.color?lt(this.color):this.resolveDark()?"244,244,245":"17,17,20";
Ot(this.ctx,this.props.size,this.frozen,this.props.state,this.props.speed,t,this.props.contrast,this.props.shape,this.props.text,this.props.density,this.props.layers,this.props.dotScale,this.props.tilt,this.props.rotation,this.props.depth)}destroy(){this.io.disconnect(),document.removeEventListener("visibilitychange",this.onVis),this.mo.disconnect(),this.mq.removeEventListener("change",this.onMq);
const t=Y.indexOf(this);
t>=0&&Y.splice(t,1)}}const Bt=[["working","Working"],["sweep","Sweep"],["shake","Shake"],["listening","Listening"],["network","Network"],["spin","Spin"],["breathing","Breathing"],["twinkle","Twinkle"],["pulse","Pulse"],["tide","Tide"],["aurora","Aurora"],["spiral","Spiral"]];
export { Dt as ThinkingOrbRuntime }
